---
title: "NBME Edits - FACS"
author: "Alina Kline-Schoder"
date: "6/25/2022"
output: pdf_document
---

```{r setup, include=FALSE}
remove(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rstatix)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(viridis)
library(Seurat)
library(RColorBrewer)
my_comparisons <- list( c("Naive", "1d"), c("Naive", "3d"), c("1d", "3d") )

ColorsGroup_NoSham<-c("#FFFFFF","#75A0B2","#205F83","gray","gray")
Colors_FUS_Group_Broad<-c("#FFFFFF","#A3A3A3","#75A0B2")
setwd("/Users/alinakline-schoder/Documents/Papers/MicrogliaPaper-Joint/Edits/2022_0630/2022_MGValidationFACSResults/")
Data<-read.csv('More-Table 1.csv')

Data_Long<-pivot_longer(Data,cols = colnames(Data)[6:9])
Data_Long$Group<-factor(Data_Long$Group,levels = c("Naive","1d","3d"))
Data_Long<-Data_Long[!is.na(Data_Long$Group),]

Data_Long$name<-recode(Data_Long$name,
                       "PH.GFP..GFP."="Phagocytosis (within GFP+)",
                       "CD45.Median..of.singlets."="CD45 MFI (within Singlets)",
                       "CD9.Median..of.singlets."="CD9 MFI (within GFP+)")

Sub<-Data_Long[Data_Long$name %in% c("CD45 MFI (within Singlets)"),]
Bar1<-ggplot(Sub,aes(x=Group,y=value))+facet_wrap(~name,scales = "free")+geom_boxplot(color="black",aes(fill=Group))+geom_point (color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+theme(legend.position="none",
        plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        axis.title.x = element_blank(),
        panel.grid = element_blank()) + facet_wrap(~name,scales="free",nrow=1)+ylab("Median Fluorescence Intensity") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=3)


Sub<-Data_Long[Data_Long$name %in% c("CD9 MFI (within GFP+)"),]
Bar4<-ggplot(Sub,aes(x=Group,y=value))+facet_wrap(~name,scales = "free")+geom_boxplot(color="black",aes(fill=Group))+geom_point(color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+theme(legend.position="none",
        plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        axis.title.x = element_blank(),
        panel.grid = element_blank()) + facet_wrap(~name,scales="free",nrow=1)+ylab("Median Fluorescence Intensity") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=3)



Sub<-Data_Long[Data_Long$name %in% c("Phagocytosis (within GFP+)"),]
#Data_Long$name<-recode(Data_Long$name,
#                       "Ph."="PH+",
#                       "CD45."="CD45+",
#                       "CD9."="CD9+")

Bar3<-ggplot(Sub,aes(x=Group,y=value))+facet_wrap(~name,scales = "free")+geom_boxplot(color="black",aes(fill=Group))+geom_point(color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+theme(legend.position="none",
        plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        axis.title.x = element_blank(),
        panel.grid = element_blank()) + facet_wrap(~name,scales="free",nrow=1)+ylab("PhRodo positive (%)") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=3)

Bar1
Bar3
Bar4
library(cowplot)
plot_grid(Bar1,Bar3,Bar4)
```

# plot old

# Boxplot
```{r}
ColorsGroup<-c("#FFFFFF","#A3A3A3","#75A0B2","#205F83")
Colors_FUS_Group_Broad<-c("#FFFFFF","#A3A3A3","#75A0B2")
setwd("/Users/alinakline-schoder/Documents/Papers/MicrogliaPaper-Joint/Edits/2022_0630/InfiltrationData/")
FACS<-read.csv('AllData-Table 1.csv')
FACS<-na.omit(FACS)
FACS<-separate(FACS,"Group",sep="_",into=c("Time","Group"),remove=FALSE)
FACS<-na.omit(FACS)
FACS <- FACS[FACS$Time!="120",]
FACS <- FACS[FACS$Time!="672",]
FACS$Time<-factor(FACS$Time)
FACS$Time<-recode(FACS$Time,"0"="Naive",
                          "24"="1d",
                          "72"="3d")
Colorssub<-ColorsGroup[3:4]
df <- FACS
df <- FACS[FACS$Group %in% c("Control","FUS/MB"),]
my_comparisons <- list( c("Naive", "1d"), c("Naive", "3d"), c("1d", "3d") )
df$Lab<-"Normalized Brain Macrophage Cell Count"
Flow<-ggplot(df,aes(x=Time,y=Phagocytes))+facet_wrap(~Lab,scales = "free")+geom_boxplot(color="black",aes(fill=Time))+geom_point(color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+theme(legend.position="none",
        plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        axis.title.x = element_blank(),
        panel.grid = element_blank()) +ylab("Normalized Brain Macrophage Cell Count") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=3)


setwd("/Users/alinakline-schoder/Documents/Papers/MicrogliaPaper-Joint/Edits/2022_0630/InfiltrationData/")
FACS<-read.csv('AllData-Table 1.csv')
FACS<-na.omit(FACS)
FACS<-separate(FACS,"Group",sep="_",into=c("Time","Group"),remove=FALSE)
FACS<-na.omit(FACS)
FACS <- FACS[FACS$Time!="120",]
FACS <- FACS[FACS$Time!="672",]
FACS <- FACS[FACS$Group!="MB",]
FACS <- FACS[FACS$Group!="FUS",]

FACS$Time<-factor(FACS$Time)
FACS$Time<-recode(FACS$Time,"0"="Naive",
                          "24"="1d",
                          "72"="3d")
#Colorssub<-ColorsGroup[3:4]
#FACS <- FACS[!(FACS$Group %in% c("Control")),]
FACS$Group<-recode(FACS$Group,
                   "FUS/MB"="FUS-BBBO",
                   "Control"="Naive")
FACS$lab<-"Normalized Brain Macrophage Count"
my_comparisons <- list(c("Naive", "1d"), c("Naive", "3d"), c("1d", "3d") )
Flow<-ggplot(FACS,aes(x=Time,y=Phagocytes))+geom_boxplot(color="black",aes(fill=Time))+facet_wrap(~lab,scales = "free")+geom_point(color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+theme(legend.position="none",
        plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        axis.title.x = element_blank(),
        panel.grid = element_blank()) +ylab("Normalized Brain Macrophage Cell Count") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=3)


```

```{r}
plot_grid(Flow,Bar1,Bar4,Bar3,nrow=2,align = "hv",axis = "lrtb",labels = c("a","b","c","d"))
ggsave("MGValFACS.png",width = 10,height = 6.5,units = "in",bg = "white")
```


