---
title: "Integrating Data"
author: Alina Kline-Schoder
date: | 
      | Started on 04/19/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---
# Microglia Data analysis

```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(Seurat)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(reshape2)
library(BiocManager)
library(rhdf5)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(gridExtra)
library(here)
library(ggrepel)
library(scrattch.hicat)
setwd("F:/Data/Sequencing/SavedData")
load("5-MicrogliaFigures.RData")
setwd("F:/Data/Sequencing/Files/")
source("Ontology.R")
DefaultAssay(Microglia)<-"RNA"
logFC<-0.5
p_val<-0.05
```
  
# hicat
```{r}
norm.dat <- Matrix(cpm(Microglia@assays$RNA@counts), sparse = TRUE)
norm.dat@x <- log2(norm.dat@x+1)
select.cells<-colnames(Microglia)
Microglia@assays$Hicat<-CreateAssayObject(norm.dat)
DefaultAssay(Microglia)<-"Hicat"
Microglia<-FindVariableFeatures(Microglia)
Microglia <- ScaleData(Microglia, verbose = FALSE)
Microglia <- RunPCA(Microglia, npcs = 50, verbose = FALSE)
Microglia <- RunUMAP(Microglia, reduction = "pca", dims = 1:20)
```

```{r}
library(Matrix)
de.param <- de_param(padj.th     = 0.05, 
                     lfc.th      = 1, 
                     low.th      = 1, 
                     q1.th       = 0.3, 
                     q.diff.th   = 0.7, 
                     de.score.th = 70,
                     min.cells = 50)

result <- run_consensus_clust(norm.dat, 
                              niter = 20, 
                              de.param = de.param, 
                              dim.method = "pca", 
                              output_dir = "Microglia_cc_0770")

Microglia$hicat_clusters<-result$cl.result$cl
DimPlot(Microglia,group.by = "hicat_clusters")
```



```{r}
HomeostaticClusters<-data.frame(genes=c("Tmem119","Sparc","Hexb","Cx3cr1"),type="Homeostatic")
Clus7<-data.frame(genes=c("Ccr1"),type="Ccr1")
Proliferation<-data.frame(genes=c("Mki67","Top2a","Cdk1"),type="Proliferation") #Cluster 10
ERG<-data.frame(genes=c("Ccl4","Fos","Egr1"),type="Early Response") #cluster 12
Interferon<-data.frame(genes=c("Ifit3","Ifitm3","Ifi35"),type="Interferon") #cluster 6
Cpe<-data.frame(genes=c("Cpe","Mt3","Slc1a2"),type= "Cpe")#cluster 8
DAM<-data.frame(genes=c("Cd9","Lpl","Spp1","Cst7","Apoe","Ctsb","Cd63","Lgals1"),type="DAM")
test<-data.frame(genes=c("Cd34"),type="Progenitors")

Genes<-rbind(HomeostaticClusters,Clus7,ERG,Interferon,Cpe,DAM,Proliferation,test)
Genes$type<-factor(Genes$type)
DefaultAssay(Microglia)<-"SCT"
dat<-DotPlot(Microglia,group.by = "hicat_clusters",features = Genes$genes)
dat<-as.data.frame(dat$data)
dat$gene.type<-Genes[dat$features.plot,]$type
dat$cell.type<-recode(dat$id,
                     "1"="Homeostatic",
                     "2"="Homeostatic",
                     "3"="Homeostatic",
                     "4"="Early Response",
                     "6"="Early Response",
                     "7"="DAM",
                     "9"="Homeostatic",
                     "11"="Interferon",
                     "12"="Proliferation",
                     "13"="Proliferation",
                     "14"="Homeostatic")
dat$cell.type<-ordered(dat$cell.type,levels=c("Homeostatic","DAM","Early Response","Interferon","Proliferation","Progenitors","Ccr1","Cpe"))
dat$gene.type<-ordered(dat$gene.type,levels=c("Homeostatic","DAM","Early Response","Interferon","Proliferation","Progenitors","Ccr1","Cpe"))
ggplot(dat,aes(x=id,y=features.plot))+
  geom_rect(xmin=as.numeric(dat$id)-.5,xmax=as.numeric(dat$id)+.5,ymin=-Inf,ymax=Inf,alpha=0.025) +
  geom_point(aes(color=avg.exp.scaled,size=pct.exp)) +
  geom_tile(aes(y=0,x=id),height=0.1) + 
  facet_grid(gene.type~cell.type, space = "free",scales = "free",shrink=FALSE) +
  theme_bw() +
  theme(axis.text.x = element_text(angle=45,size=8,vjust=1,hjust=1),
        plot.background = element_blank(),
        strip.background = element_rect(fill=NA,color=NA),
        axis.title.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.text = element_text(size=8),
        legend.title = element_text(size=8),
        legend.key.height = unit(0.75,"mm"),
        plot.margin = margin(0,0,0,0,"cm"),
        panel.grid = element_blank()) + scale_color_viridis_b(guide=guide_colorbar(title.position = "top",title="Expression"))+
  scale_size_continuous(limits=c(1,100),breaks = c(1,50,100),guide=guide_legend(title.position = "top",title = "Cells Expressing (%)"),range=c(1,4))

Microglia$cluster.type<-recode(Microglia$hicat_clusters,
                     "1"="Homeostatic",
                     "2"="Homeostatic",
                     "3"="Homeostatic",
                     "4"="Early Response",
                     "6"="Early Response",
                     "7"="DAM",
                     "9"="Homeostatic",
                     "11"="Interferon",
                     "12"="Proliferation",
                     "13"="Proliferation",
                     "14"="Homeostatic")

setwd("F:/Data/Sequencing/Seq2_SavedData/")
save(Microglia,file = "Seq1_Microglia.RData")
```

```{r}
tab<-as.data.frame(table(Microglia$Treatment,Microglia$cluster.type))
tot<-as.data.frame(table(Microglia$Treatment))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
ggplot(tab,aes(x=Var2,y=Var1,fill=Freq_Norm))+geom_tile()+scale_fill_gradientn(colours = c("white","black"),limits=c(0,20),guide=guide_colorbar(title.position = "top",title = "Frequency (%)"))+geom_label(aes(label=round(Freq_Norm,3)))
```

