---
title: "Microglia Figure"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---


```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(RColorBrewer)
library(ComplexHeatmap)
library(ggrepel)
library(circlize)
library(tidyr)
library(dplyr)
library(sjmisc)
library(viridis)
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
ColorsTreatment<-c("#FFFFFF","#A3A3A3","#9781B1","#54426B")
#names(ColorsTreatment)<-c("Naive","Sham","1d","3d")
LinesTreatment<-c("#A3A3A3",ColorsTreatment[2:4])
names(LinesTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
setwd("/media/alina/Backup1/Scripts/R/FUSMicrogliaClean_SavedData/")
load("5-MicrogliaFigures.RData")
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))
MicrogliaClusterColors<-c("#DC7F9B","#DC7F9B","#DC7F9B","#DC7F9B","#DC7F9B", "#DC7F9B","#DC7F9B", "#DC7F9B", "#DC7F9B", "#DC7F9B", "#D56D02","#BB3E03","#94D2BD")
MicrogliaClusterColors2<-c("#84b082","#AF91BA","#DC7F9B","#8F938E","#E55934", "#70B8CC","#4281a4", "#84b082", "#A1E8CC", "#EBE1A0", "#D56D02","#BB3E03","#94D2BD")
```

# 1d Volcano
```{r}
toptable <- as.data.frame(clustermarkers_1d)
toptable$lab <- rownames(clustermarkers_1d)
Genes<-c("Ccl4","Spp1","Cd63","P2ry12")
toptable$color<-"red"
toptable[toptable$p_val_adj>0.05,]$color<-"black"
toptable[abs(toptable$avg_log2FC)<0.5,]$color<-"black"
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))
volc1d<-ggplot(toptable, aes(x = xvals, y = yvals)) + 
  geom_point(na.rm = TRUE,size=0.1,color=toptable$color) + 
  xlab(xlab) + 
  ylab(ylab) + 
  geom_label_repel(aes(label=lab),size=2,label.padding = unit(0.1, "lines"),max.overlaps = 100) +
  theme(panel.grid = element_blank(),
        plot.margin=margin(0.3,0.3,0,0.3,"cm"),
        panel.background = element_blank(),
        plot.title = element_text(size=8),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=6),
        axis.title = element_text(size=8)) +  scale_y_continuous(expand=c(0,0))+ggtitle("1d v Sham")
```


# 1d Volcano
```{r}
toptable <- as.data.frame(clustermarkers_3d)
toptable$lab <- rownames(clustermarkers_3d)
Genes<-c("Ccl4","Spp1","Cd63","Mki67","Cd9","Tubb5")
toptable$color<-"red"
toptable[toptable$p_val_adj>0.05,]$color<-"black"
toptable[abs(toptable$avg_log2FC)<0.5,]$color<-"black"
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))
Volc3d<-ggplot(toptable, aes(x = xvals, y = yvals)) + 
  geom_point(na.rm = TRUE,size=0.1,color=toptable$color) + 
  xlab(xlab) + 
  ylab(ylab) + 
  geom_label_repel(aes(label=lab),size=2,label.padding = unit(0.1, "lines"),max.overlaps = 100) +
  theme(panel.grid = element_blank(),
        plot.margin=margin(0.3,0.3,0,0.3,"cm"),
        panel.background = element_blank(),
        plot.title = element_text(size=8),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=6),
        axis.title = element_text(size=8))+ scale_y_continuous(expand=c(0,0))+ggtitle("3d v Sham")
```
### Treatment Ontology
```{r}
Onto_1d$Time<-"1d BBBO"
Onto_3d$Time<-"3d BBBO"
Onto_All<-rbind(Onto_1d,Onto_3d)
BP<-c("phagocytic vesicle",
      "macrophage chemotaxis",
      "lysosome",
      "extracellular exosome",
      "regulation of immune response",
      "cell population proliferation",
      "response to stress",
      "chemokine receptor binding",
      "cell chemotaxis",
      "cell cycle")

OntoPlotdata<-Onto_All[Onto_All$Term %in% BP,]
OntoPlotdata$Time<-recode(OntoPlotdata$Time,
                          "1d BBBO"="1d",
                          "3d BBBO"="3d")
OntoPlotdata$Time<-as.factor(OntoPlotdata$Time)
KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(italic(P[Fis]))
library(scales) 
OntoPlot<-ggplot(OntoPlotdata,aes(x=Time,y=Term,color=-log(PVal_KS),size=PCT))+
  geom_point()+
  theme_minimal()+scale_color_viridis(guide=guide_colorbar(title=KSLab,title.position = "top"),option = "plasma")+ scale_size_continuous(guide=guide_legend(title="Genes (%)",title.position = "top"),breaks = c(25,50,75),limits=c(25,75),range = c(0.5,4))+
  theme(legend.position = "right",
        axis.text = element_text(size=10),
        legend.direction = "vertical",
        legend.box = "vertical",
        legend.key.height = unit(0.3,"cm"),
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        plot.margin = margin(0.25,0.5,0.25,0.25,"cm"),
        axis.title = element_blank(),
        legend.spacing.x = unit(0,"cm"),
        legend.text = element_text(size=8),
        legend.title = element_text(size=8))
```

# phase barchart
```{r}
tab<-as.data.frame(table(Microglia$Treatment,Microglia$Phase))
tot<-as.data.frame(table(Microglia$Treatment))
tab$Full<-tot[paste(tab$Var1,tab$Var2),]$Freq
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
tab$Var1<-recode(tab$Var1,
                 "3d BBBO"="3d",
                 "1d BBBO"="1d")
BC1<-ggplot(tab,aes(x=Var2,y=Var1,fill=Freq_Norm))+geom_tile()+scale_fill_gradientn(colours = c("white","black"),limits = c(0,100),breaks=c(0,100),guide=guide_colorbar(title.position = "top",title = "Frequency (%)",label.position="bottom"))+geom_tile(aes(y=Var1,x=0.5),width=0.166,fill=ColorsTreatment[tab$Var1],color=LinesTreatment[tab$Var1])+scale_y_discrete(expand=c(0,0))+theme_minimal()+scale_y_discrete(expand=c(0,0))+scale_x_discrete(expand=c(0,0))+theme(legend.position = "top")+xlab("Assigned Phase")+
  theme(legend.key.height = unit(0.1,"cm"),
        legend.title = element_text(size=8,hjust=0.5,vjust=0),
        legend.text = element_text(size=8),
        axis.text = element_text(size=8),
        axis.title.x = element_text(size=8),
        legend.box.margin = margin(0,0,-0.5,0,"cm"),
        axis.text.x = element_text(size=8,vjust=0.75,hjust=0.5),
        axis.title.y = element_blank(),
        plot.margin = margin(0,0.5,0,0.3,"cm"),
        legend.key.width = unit(0.3,"cm"))
```

```{r}
setwd("/media/alina/Backup1/Scripts/R/FUSMicrogliaClean/Figures/IUS-2022/2022_MGValidationFACSResults/")
ColorsGroup_NoSham<-c("#FFFFFF","#9781B1","#54426B","gray","gray")
Data<-read.csv('More-Table 1.csv')
my_comparisons <- list( c("Naive", "1d"), c("Naive", "3d"), c("1d", "3d") )
Data_Long<-pivot_longer(Data,cols = colnames(Data)[6:9])
Data_Long$Group<-factor(Data_Long$Group,levels = c("Naive","1d","3d"))
Data_Long<-Data_Long[!is.na(Data_Long$Group),]
Data_Long$name<-recode(Data_Long$name,
                       "PH.GFP..GFP."="Phagocytosis",
                       "CD45.Median..of.singlets."="CD45 MFI (within GFP+)",
                       "CD9.Median..of.singlets."="CD9 MFI (within GFP+)")

Sub<-Data_Long[Data_Long$name %in% c("Phagocytosis"),]
Bar3<-ggplot(Sub,aes(x=Group,y=value))+geom_boxplot(color="black",aes(fill=Group))+geom_point(color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+theme(legend.position="none",
        plot.margin=margin(0.25,0.5,0,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=8),
        axis.title = element_text(size=8),
        axis.title.x = element_blank(),
        panel.grid = element_blank())+ylab("Phagocytosis (%)") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=2,label = "p.signif")
```


# top
```{r}
Blank<-ggplot() + theme_void()
plot_grid(OntoPlot,BC1,Bar3,nrow=1,labels = c("a","b","c"))
ggsave("IUSPoster-Microglia1.png",width = 6,height = 1.5,units = "in",bg="white")

IHC<-plot_grid(Blank,Blank,Blank,nrow=1,labels = c("a","b","c"))
ggsave("IUSPoster-Microglia3.png",width = 5,height = 2,units = "in",bg="white")

plot_grid(plot_grid(Blank,Blank,nrow=2,labels = c("a","b")),Bar3,nrow=1,labels=c("","c"),rel_widths = c(0.75,1))
ggsave("IUSPoster-Microglia2.png",width = 3.5,height = 2.25,units = "in",bg="white")
getwd()
```

```{r}
# Heatmap for lecture
clustermarkers_AllTreatment$pct.dif<-clustermarkers_AllTreatment$pct.1-clustermarkers_AllTreatment$pct.2
Genes2Plot<-clustermarkers_AllTreatment%>%
    group_by(cluster) %>%
    top_n(n = 5, wt = pct.dif)
Genes2Plot<-unique(Genes2Plot$gene)
Idents(Microglia)<-"Treatment"
Sub<-subset(Microglia,downsample=1000)
Genes2Plot<-c("P2ry12","Cx3cr1","Aif1","Ccl3","Ccl4","Fos","Mki67","Top2a","Ifi30")
Data<-t(as.matrix(Sub@assays$RNA@data[Genes2Plot,]))
Data<-cbind(as.data.frame(Data),Sub$seurat_clusters,Sub$Treatment)
colnames(Data)[dim(Data)[2]-1]<-"Cluster"
colnames(Data)[dim(Data)[2]]<-"Treatment"
Data<-Data[order(Data$Treatment,Data$Cluster),]
Treatment<-Data$Treatment
Treatment<-recode(Treatment,
                  "1d BBBO"="1d",
                  "3d BBBO"="3d")
Cluster<-Data$Cluster
Data<-Data[,1:(dim(Data)[2]-2)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(ColorsTreatment)<-levels(Microglia$Treatment)
names(MicrogliaClusterColors)<-levels(Microglia$seurat_clusters)

col_ha=HeatmapAnnotation(Treat=Treatment,col=list(
  Treat=c("Naive"="#FFFFFF",
          "Sham"="#A3A3A3",
          "1d"="#9781B1",
          "3d"="#54426B")),show_legend = F,show_annotation_name = F,border=T)

HM<-Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            show_column_names = FALSE,
            row_names_side = "left",
            top_annotation = col_ha,
            col=col_fun,
            row_names_gp = gpar(fontsize=8,family="Arial"),
            column_split = Treatment,
            column_title_gp = gpar(fontsize=8,family="Arial"),
        heatmap_legend_param = list(title="Expression ",title_gp=gpar(fontsize=8,family="Arial"),labels_gp=gpar(fontsize=6),direction="vertical",position="right"))

HM_Ready<-plot_grid(grid.grabExpr(draw(HM,heatmap_legend_side="right")))
```


```{r}
plot_grid(HM_Ready,OntoPlot+theme(plot.margin = margin(0.25,0.25,0.25,0.25,"cm")),nrow=1,labels = c("a","b"))
ggsave("MicrogliaDEG.png",width=8,height=2,units = "in",bg = "white")
```
