---
title: "IUS Figures"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---
# IUS Figures

```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(circlize)
library(ggrepel)
library(viridis)
#setwd("F:/Data/Sequencing/SavedData")
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
ColorsTreatment<-c("#FFFFFF","#A3A3A3","#9781B1","#54426B")
names(ColorsTreatment)<-c("Naive","Sham","1d","3d")
LinesTreatment<-c("#A3A3A3",ColorsTreatment[2:4])
names(LinesTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
setwd("/media/alina/Backup1/Scripts/R/FUSMicrogliaClean_SavedData/")
load("5-MicrogliaFigures.RData")
#load("DAMMarkers_new.RData")
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))

MicrogliaClusterColors<-c("#DC7F9B","#DC7F9B","#DC7F9B","#DC7F9B","#DC7F9B", "#DC7F9B","#DC7F9B", "#DC7F9B", "#DC7F9B", "#DC7F9B", "#D56D02","#BB3E03","#94D2BD")
MicrogliaClusterColors2<-c("#84b082","#AF91BA","#DC7F9B","#8F938E","#E55934", "#70B8CC","#4281a4", "#84b082", "#A1E8CC", "#EBE1A0", "#D56D02","#BB3E03","#94D2BD")
names(MicrogliaClusterColors)<-levels(Microglia$seurat_clusters)
MicrogliaClusterColors[levels(Microglia$seurat_clusters)!="2"]<-"gray"
```

# Poster



## DAM
### DAM Highlighted on Microglia UMAP
```{r}
Dim1<-DimPlot(Microglia,group.by = "seurat_clusters",cols=MicrogliaClusterColors,label=FALSE)+theme(plot.title = element_blank(),axis.ticks = element_blank(),axis.text = element_blank(),legend.position = "none")+scale_y_continuous(limits=c(-9.5,7))+scale_x_continuous(limits=c(-4.5,7.25))
```


### DAM Volcano 
```{r}
toptable <- as.data.frame(DAMMarkers)
toptable$lab <- rownames(DAMMarkers)
Genes<-c("Cd9","Spp1","Cst7","Tmem119","P2ry12","Ctsb","Cd63","Cx3cr1")
toptable$color<-"red"
toptable[toptable$p_val_adj>0.05,]$color<-"black"
toptable[abs(toptable$avg_log2FC)<0.5,]$color<-"black"
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))
DAMVolc<-ggplot(toptable, aes(x = xvals, y = yvals)) + 
  geom_point(na.rm = TRUE,size=0.1,color=toptable$color) + 
  xlab(xlab) + 
  ylab(ylab) + 
  geom_label_repel(aes(label=lab),size=2,label.padding = unit(0.1, "lines"),max.overlaps = 100) +
  theme(panel.grid = element_blank(),
        plot.margin=margin(0.25,0.5,0,0.5,"cm"),
        panel.background = element_blank(),
        plot.title = element_blank(),
        axis.text = element_text(size=6),
        axis.title = element_text(size=8))+scale_y_continuous(expand=c(0,0))
```

### DAM Percentage
```{r}
tab<-as.data.frame(table(Microglia$orig.ident,Microglia$Treatment,Microglia$seurat_clusters))
tab<-tab[tab$Var3=="2",]

Tota<-as.data.frame(table(Microglia$orig.ident,Microglia$Treatment))
Tota$Full<-paste(Tota$Var1,Tota$Var2)
tab$Full<-paste(tab$Var1,tab$Var2)
rownames(Tota)<-Tota$Full
tab$Total<-Tota[tab$Full,]$Freq
tab<-tab[tab$Total>0,]
tab$Freq_Adj<-tab$Freq/tab$Total
tab$Var2<-recode(tab$Var2,"1d BBBO"="1d",
                 "3d BBBO"="3d")
Percent<-ggplot(tab,aes(x=Var2,y=Freq_Adj*100))+geom_boxplot(color="black",aes(fill=Var2))+geom_point(color="black")+scale_fill_manual(values=ColorsTreatment)+theme(legend.position="none",
        plot.margin=margin(0.25,0.5,0,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=6),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=6),
        axis.title = element_text(size=8),
        axis.title.x = element_blank(),
        panel.grid = element_blank())+stat_compare_means(method="anova",label.y = 55,size=2) + scale_y_continuous(expand = c(0,0),limits = c(0,60))+ylab("DAM (% of microglia)")
```


### DAM Ontology
```{r}
Terms<-c("glial cell development",
         "gliogenesis",
         "macrophage migration",
         "phagocytic vesicle",
         "lysosome",
         "response to stimulus",
         "cell chemotaxis",
         "regulation of cell cycle",
         "immune response")
DAM_Onto_1d$Treatment<-"1d"
DAM_Onto_3d$Treatment<-"3d"
All<-rbind(DAM_Onto_1d,DAM_Onto_3d)
OntoPlotdata<-All[All$Term %in% Terms,]
KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(italic(P[Fis]))
library(scales) 
OntoPlot<-ggplot(OntoPlotdata,aes(x=Treatment,y=Term,color=-log(PVal_KS),size=PCT))+
  geom_point()+
  theme_minimal()+scale_color_viridis(guide=guide_colorbar(title=KSLab,title.position = "top"),option = "plasma")+ scale_size_continuous(guide=guide_legend(title="Genes (%)",title.position = "top"),breaks = c(20,35,50),limits=c(20,50),range = c(0.5,4))+
  theme(legend.position = "right",
        axis.text = element_text(size=10),
        legend.direction = "vertical",
        legend.box = "vertical",
        legend.key.height = unit(0.3,"cm"),
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        plot.margin = margin(0.25,0.5,0.25,0.25,"cm"),
        axis.title = element_blank(),
        legend.spacing.x = unit(0,"cm"),
        legend.text = element_text(size=8),
        legend.title = element_text(size=8))
```
### validation plot
```{r}
my_comparisons <- list( c("Naive", "1d"), c("Naive", "3d"), c("1d", "3d") )
ColorsGroup_NoSham<-c("#FFFFFF","#9781B1","#54426B","gray","gray")
Colors_FUS_Group_Broad<-c("#FFFFFF","#A3A3A3","#9781B1","#54426B")
setwd("/media/alina/Backup1/Scripts/R/Seq1-2022/Figures/IUS-2022/2022_MGValidationFACSResults/")
Data<-read.csv('More-Table 1.csv')

Data_Long<-pivot_longer(Data,cols = colnames(Data)[6:9])
Data_Long$Group<-factor(Data_Long$Group,levels = c("Naive","1d","3d"))
Data_Long<-Data_Long[!is.na(Data_Long$Group),]

Data_Long$name<-recode(Data_Long$name,
                       "PH.GFP..GFP."="Phagocytosis (within GFP+)",
                       "CD45.Median..of.singlets."="CD45 MFI (within GFP+)",
                       "CD9.Median..of.singlets."="CD9 MFI (within GFP+)")

Sub<-Data_Long[Data_Long$name %in% c("CD9 MFI (within GFP+)"),]
Bar4<-ggplot(Sub,aes(x=Group,y=value))+geom_boxplot(color="black",aes(fill=Group))+geom_point(color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+theme(legend.position="none",
        plot.margin=margin(0.25,0.5,0.25,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        plot.title = element_text(size=8),
        strip.text = element_text(size=8),
        axis.text = element_text(size=6),
        axis.title = element_text(size=8),
        axis.title.x = element_blank(),
        panel.grid = element_blank())+ylab("Cd9 MFI") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=2,label = "p.signif")
```


### Putting it all together
```{r}
plot_grid(Dim1+theme(axis.title = element_text(size=6),axis.line = element_line(size=0.25)),DAMVolc+theme(axis.line = element_line(size=0.25)),Percent+theme(axis.line = element_line(size=0.25)),OntoPlot+theme(legend.text = element_text(size=6),axis.text = element_text(size=6),plot.margin = margin(0,0,0,10)),nrow=1,labels=c("a","b","c","d"),rel_widths = c(0.75,1,1,1.25),align = T,axis = "b")
ggsave("IUS_Poster_DAM.png",width = 9,height = 2,units = "in",bg="white")
plot_grid(OntoPlot,Bar4,nrow=1,labels=c("a","b"),rel_widths = c(0.75,1))
ggsave("IUS_Poster_DAM2.png",width = 4.25,height = 1.75,units = "in",bg="white")

```

# DAM heatmap
```{r}
library(ComplexHeatmap)
Idents(Microglia)<-"seurat_clusters"
DAM<-subset(Microglia,idents = "2")
Idents(DAM)<-"Treatment"
marks_1d$pct.dif<-marks_1d$pct.1-marks_1d$pct.2
marks_3d$pct.dif<-marks_3d$pct.1-marks_3d$pct.2
Idents(DAM)<-"Treatment"
Sub<-subset(DAM,downsample=200)
Genes2Plot1<-marks_1d%>%
    top_n(n = 10, wt = pct.dif)

Genes2Plot2<-marks_3d%>%
    top_n(n = 10, wt = pct.dif)


Genes2Plot<-unique(c(rownames(Genes2Plot1),rownames(Genes2Plot2)))
Genes2Plot<-c("Cd9","Cd63","Ccl3","Ccl4","Fos","Mki67","Top2a","Ifi30")
Data<-t(as.matrix(Sub@assays$RNA@data[Genes2Plot,]))
Data<-cbind(as.data.frame(Data),Sub$seurat_clusters,Sub$Treatment)
colnames(Data)[dim(Data)[2]-1]<-"Cluster"
colnames(Data)[dim(Data)[2]]<-"Treatment"
Data<-Data[order(Data$Treatment,Data$Cluster),]
Treatment<-Data$Treatment
Treatment<-recode(Treatment,
                  "1d BBBO"="1d",
                  "3d BBBO"="3d")
Cluster<-Data$Cluster
Data<-Data[,1:(dim(Data)[2]-2)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(ColorsTreatment)<-levels(Microglia$Treatment)
names(MicrogliaClusterColors)<-levels(Microglia$seurat_clusters)

col_ha=HeatmapAnnotation(Treat=Treatment,col=list(
  Treat=c("Naive"="#FFFFFF",
          "Sham"="#A3A3A3",
          "1d"="#9781B1",
          "3d"="#54426B")),show_legend = F,show_annotation_name = F,border=T)

HM<-Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            show_column_names = FALSE,
            row_names_side = "left",
            top_annotation = col_ha,
            col=col_fun,
            row_names_gp = gpar(fontsize=8,family="Arial"),
            column_split = Treatment,
            column_title_gp = gpar(fontsize=8,family="Arial"),
        heatmap_legend_param = list(title="Expression ",title_gp=gpar(fontsize=8,family="Arial"),labels_gp=gpar(fontsize=6),direction="vertical",position="right"))

HM_Ready<-plot_grid(grid.grabExpr(draw(HM,heatmap_legend_side="right")))
```


```{r}
plot_grid(HM_Ready,OntoPlot+theme(plot.margin = margin(0.25,0.25,0.25,0.25,"cm")),nrow=1,labels = c("a","b"))
ggsave("IUS_LectureDAM.png",width=8,height=2,units = "in",bg = "white")
```

```{r}
Terms<-c("cell chemotaxis",
         "macrophage migration",
         "phagocytic vesicle",
         "lysosome",
         "response to stimulus",
         "cell chemotaxis",
         "immune response")
DAM_Onto_1d$Treatment<-"1d"
DAM_Onto_3d$Treatment<-"3d"
All<-rbind(DAM_Onto_1d,DAM_Onto_3d)
OntoPlotdata<-All[All$Term %in% Terms,]
KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(italic(P[Fis]))
library(scales) 
OntoPlot<-ggplot(OntoPlotdata,aes(x=Treatment,y=Term,color=-log(PVal_KS),size=PCT))+
  geom_point()+
  theme_minimal()+scale_color_viridis(guide=guide_colorbar(title=KSLab,title.position = "top"),option = "plasma")+ scale_size_continuous(guide=guide_legend(title="Genes (%)",title.position = "top"),breaks = c(20,35,50),limits=c(20,50),range = c(0.5,4))+
  theme(legend.position = "right",
        axis.text = element_text(size=10),
        legend.direction = "vertical",
        legend.box = "vertical",
        legend.key.height = unit(0.3,"cm"),
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        plot.margin = margin(0.25,0.5,0.25,0.25,"cm"),
        axis.title = element_blank(),
        legend.spacing.x = unit(0,"cm"),
        legend.text = element_text(size=8),
        legend.title = element_text(size=8))
```


```{r}
plot_grid(Dim1,Percent,OntoPlot+theme(plot.margin = margin(0.25,0.25,0.25,0.25,"cm")),nrow=1,labels = c("a","b","c"),rel_widths = c(1,0.75,1.25),align = "h",axis = "tb")
ggsave("IUSProceeingsDAM.png",width=8,height=2,units = "in",bg = "white")

```

