---
title: "Microglia Figure"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---


```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(RColorBrewer)
library(ComplexHeatmap)
library(ggrepel)
library(ggVennDiagram)
library(circlize)
library(tidyr)
library(dplyr)
library(sjmisc)
library(viridis)
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
ColorsTreatment<-c("#FFFFFF","#A3A3A3","#75A0B2","#205F83")
LinesTreatment<-c("#A3A3A3",ColorsTreatment[2:4])
names(LinesTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
setwd("F:/Data/Sequencing/SavedData")
#setwd("/Users/alinakline-schoder/Documents/Github.nosync/Data")
load("3-AllCells.RData")
load("5-MicrogliaFigures.RData")
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))
ColorsAllClusters[!str_contains("Microglia",levels(Integrated$cluster_full),switch = T)]<-"gray"
ColorsAllClusters[str_contains("Microglia",levels(Integrated$cluster_full),switch = T)]<-"red"
```
# Microglia Highlighted
```{r}
MicrogliaClusterColors<-c("#4FB3AA","#E9D8A6","#CA6702","#057985","#AE2012", "#BFD5B2","#0A9396", "#FFE987", "#F7C244", "#F4E197", "#D56D02","#BB3E03","#94D2BD")
Idents(Integrated)<-"cluster_full"
Highlight<-DimPlot(Integrated,group.by = "cluster_full",cols=ColorsAllClusters,label=FALSE)+NoLegend()+
  theme(plot.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        panel.spacing = unit(0,"cm"),
        panel.border = element_rect(color="black"),
        panel.background = element_rect(fill='transparent'))
```


# Treatment Comparison
## Treatment comparison
### Treatment Ontology
```{r}
Onto_1d$Time<-"1d BBBO"
Onto_3d$Time<-"3d BBBO"
Onto_All<-rbind(Onto_1d,Onto_3d)
BP<-c("phagocytic vesicle",
      "extracellular vesicle",
      "chemokine activity",
      "macrophage chemotaxis",
      "lysosome",
      "microglial cell activation",
      "regulation of immune response",
      "regulation of myeloid cell differentiation",
      "cell cycle",
      "endosome",
      "late endosome",
      "external encapsulating structure",
      "response to interferon-gamma",
      "response to stress",
      "chemokine receptor binding",
      "glial cell migration",
      "gliogenesis")

OntoPlotdata<-Onto_All[Onto_All$Term %in% BP,]
OntoPlotdata$Time<-as.factor(OntoPlotdata$Time)
OntoPlotdata$Time<-recode(OntoPlotdata$Time,
                          "1d BBBO"="1d",
                          "3d BBBO"="3d")
KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(italic(P[Fis]))
library(scales) 
OntoPlotdata$Group<-recode(OntoPlotdata$Group,"Biological Process"="BP",
                           "Cellular Component"="CC",
                           "Molecular Function"="MF")
OntoPlot<-ggplot(OntoPlotdata,aes(x=Time,y=Term,color=-log(PVal_KS),size=PCT))+
  facet_grid(Group~.,scales = "free",space = "free")+
  geom_point()+
  theme_minimal()+scale_color_viridis()+scale_color_viridis(guide=guide_colorbar(title=KSLab,title.position = "top"))+ scale_size_continuous(guide=guide_legend(title="Genes (%)",title.position = "top"),breaks = c(25,50,75),limits=c(25,75),range = c(0.5,4))+
  theme(legend.position = "right",
        axis.text.y = element_text(size=6),
        legend.direction = "vertical",
        legend.box = "vertical",
        legend.key.width = unit(2,"mm"),
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        plot.margin = margin(0.5,0.5,0.5,0,"cm"),
        axis.title = element_blank(),
        legend.spacing.y = unit(0,"cm"),
        legend.box.spacing = margin(-0.5,0.5,0.25,0,"cm"),
        legend.text = element_text(size=6),
        legend.title = element_text(size=6),
        strip.text.y = element_text(size=10))
```


# Heatmap
```{r}
clustermarkers_AllTreatment$pct.dif<-clustermarkers_AllTreatment$pct.1-clustermarkers_AllTreatment$pct.2
Genes2Plot<-clustermarkers_AllTreatment%>%
    group_by(cluster) %>%
    top_n(n = 15, wt = pct.dif)
Genes2Plot<-unique(Genes2Plot$gene)
Idents(Microglia)<-"Treatment"
Sub<-subset(Microglia,downsample=1000)
Data<-t(as.matrix(Sub@assays$RNA@data[Genes2Plot,]))
Data<-cbind(as.data.frame(Data),Sub$seurat_clusters,Sub$Treatment)
colnames(Data)[dim(Data)[2]-1]<-"Cluster"
colnames(Data)[dim(Data)[2]]<-"Treatment"
Data<-Data[order(Data$Treatment,Data$Cluster),]
Treatment<-Data$Treatment
Cluster<-Data$Cluster
Data<-Data[,1:(dim(Data)[2]-2)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(ColorsTreatment)<-levels(Microglia$Treatment)
names(MicrogliaClusterColors)<-levels(Microglia$seurat_clusters)
Top<-columnAnnotation(Treatment=anno_simple(Treatment,height = unit(2, "mm"),col = ColorsTreatment,border = TRUE), Cluster=anno_simple(Cluster,height=unit(2,"mm"),col=MicrogliaClusterColors),show_legend=FALSE,show_annotation_name=FALSE)
HM<-Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            show_column_names = FALSE,
            row_names_side = "left",
            top_annotation = Top,
            col=col_fun,
            show_heatmap_legend = FALSE,
            row_names_gp = gpar(fontsize=6,family="Arial"),
            column_split = Treatment,
            column_title_gp = gpar(fontsize=8,family="Arial"))
HMLeg<-grid.grabExpr(draw(Legend(col_fun = col_fun, 
                                  direction = "vertical",
                                  grid_height = unit(0.5,"mm"),
                                  grid_width=unit(1,"mm"),
                                  at=c(-2,0,2),
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=6),
                                  title_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  labels = c("-2", "0", "2"))))
HM_Ready<-plot_grid(grid.grabExpr(draw(HM)),HMLeg,rel_widths = c(10,1),nrow=1)
```




# New Plots
## Cluster ID (featureplot)
```{r}
DefaultAssay(Microglia)<-"RNA"
Feat<-FeaturePlot(Microglia,features = c("Cx3cr1","Tmem119","Hexb","Cd9","Top2a","Ifitm3"),ncol=3,cols = c("#D3D3D3","red"))&theme(legend.position = "none",
                                                                                                        axis.text = element_blank(),
                                                                                                        axis.title = element_blank(),
                                                                                                        axis.ticks = element_blank(),title = element_text(size=8,vjust=-0.5),plot.margin = margin(0.2,0.2,0.2,0.2,"cm"))
```

## treatment group split by clusters
```{r}
tab<-as.data.frame(table(Microglia$Treatment,Microglia$seurat_clusters))
tot<-as.data.frame(table(Microglia$Treatment))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
BC2<-ggplot(tab,aes(x=Var1,y=Var2,fill=Freq_Norm))+geom_tile()+scale_fill_gradientn(colours = c("white","black"),limits = c(0,50),breaks=c(0,50),guide=guide_colorbar(title.position = "right",title = "Frequency (%)",label.position="right"))+geom_tile(aes(x=0.5,y=Var2),width=0.05,fill=MicrogliaClusterColors[tab$Var2])+scale_y_discrete(expand=c(0,0))+geom_tile(aes(x=Var1,y=0.5),height=0.25,fill=ColorsTreatment[tab$Var1],color=LinesTreatment[tab$Var1])+theme_minimal()+scale_y_discrete(expand=c(0,0))+scale_x_discrete(expand=c(0,0))+theme(legend.position = "right")+xlab("Treatment")+ylab("Cluster")+theme(legend.key.width = unit(0.2,"cm"),legend.title = element_text(size=8,angle=-90,hjust=0.5,vjust=-5),legend.text = element_text(size=6),axis.text = element_text(size=6),axis.title.y = element_text(size=8),legend.box.margin = margin(0,-0.5,0,-0.25,"cm"),axis.text.x = element_text(size=6,angle=45,vjust=0.75,hjust=0.5),axis.title.x = element_blank())
```

## Microglia UMAP 
```{r}
Dim<-DimPlot(Microglia,group.by = "seurat_clusters",label=TRUE,cols =MicrogliaClusterColors,label.box = TRUE,label.size = 2)+theme(plot.title = element_blank(),
                                                                                                                 axis.ticks = element_blank(),
                                                                                                                 axis.text = element_blank(),
                                                                                                                 legend.text = element_text(size=8),
        legend.key.size = unit(0.1,"mm"),
        legend.spacing = unit(0,"mm"),
        legend.position = c(0.9,0.2))+guides(color=guide_legend(override.aes = list(size=3),ncol=1))+scale_y_continuous(limits=c(-9.5,7))+scale_x_continuous(limits=c(-4.5,7.25)
)
```

## Microglia UMAP2
```{r}
Dim2<-DimPlot(Microglia,group.by = "seurat_clusters",label=FALSE,cols =MicrogliaClusterColors,label.box = FALSE,split.by = "Treatment")+theme(plot.title = element_blank(),
                                                                                                                 axis.ticks = element_blank(),
                                                                                                                 axis.text = element_blank(),
                                                                                                                 legend.text = element_text(size=8),
        legend.key.size = unit(0.1,"mm"),
        legend.spacing = unit(0,"mm"),
        legend.position = c(0.9,0.2))+guides(color=guide_legend(override.aes = list(size=3),ncol=1))
```






## Phase

### Treatment by Phase barplot
```{r}
tab<-as.data.frame(table(Microglia$Treatment,Microglia$Phase))
tot<-as.data.frame(table(Microglia$Treatment))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
BC1<-ggplot(tab,aes(x=Var2,y=Var1,fill=Freq_Norm))+geom_tile()+scale_fill_gradientn(colours = c("white","black"),limits = c(0,100),breaks=c(0,100),guide=guide_colorbar(title.position = "top",title = "Frequency (%)",label.position="bottom"))+geom_tile(aes(y=Var1,x=0.5),width=0.166,fill=ColorsTreatment[tab$Var1],color=LinesTreatment[tab$Var1])+scale_y_discrete(expand=c(0,0))+theme_minimal()+scale_y_discrete(expand=c(0,0))+scale_x_discrete(expand=c(0,0))+theme(legend.position = "top")+xlab("Assigned Phase")+
  theme(legend.key.height = unit(0.1,"cm"),
        legend.title = element_text(size=7,hjust=0.5,vjust=0),
        legend.text = element_text(size=6),
        axis.text = element_text(size=6),
        axis.title.x = element_text(size=8),
        legend.box.margin = margin(0,0,-0.5,0,"cm"),
        axis.text.x = element_text(size=6,vjust=0.75,hjust=0.5),
        axis.title.y = element_blank(),
        plot.margin = margin(-0.25,0.05,-0.25,0.25,"cm"),
        legend.key.width = unit(0.3,"cm"))
```

### Phase Score
```{r}
Idents(Microglia)<-"Treatment"
dot_data<-data.frame(Treatment=Microglia$Treatment,G1S=Microglia$G1S.Score,S=Microglia$S.Score,G2M=Microglia$G2M.Score,M=Microglia$M.Score,MG1=Microglia$MG1.Score)

dot_data <- dot_data %>%
  group_by(Treatment) %>%
  summarize(G1S=mean(G1S),S=mean(S),G2M=mean(G2M),M=mean(M),MG1=mean(MG1)) %>%
  pivot_longer(cols=c("G1S","S","G2M","M","MG1"))
dot_data$name<-ordered(dot_data$name,levels=c("G1S","S","G2M","M","MG1"))

HMPhase<-ggplot(dot_data,aes(x=name,y=Treatment,fill=value))+geom_tile()+theme_minimal()+scale_fill_gradient2(low="blue",high = "red",mid="gray",limits=c(-2,2),breaks=c(-2,2),guide=guide_colorbar(title.position = "top",title = "Score",label.position="bottom"))+geom_tile(aes(y=Treatment,x=0.5),width=0.25,fill=ColorsTreatment[dot_data$Treatment],color=LinesTreatment[dot_data$Treatment])+scale_y_discrete(expand=c(0,0))+theme_minimal()+scale_y_discrete(expand=c(0,0))+scale_x_discrete(expand=c(0,0))+theme(legend.position = "top")+xlab("Phase")+theme(
  legend.key.height = unit(0.1,"cm"),
  legend.title = element_text(size=7,hjust=0.5,vjust=0),
  legend.text = element_text(size=6),
  axis.text = element_text(size=6),
  axis.title.x = element_text(size=8),
  axis.title.y = element_blank(),
  legend.box.margin = margin(0,0,-0.5,0,"cm"),
  axis.text.x = element_text(size=6,vjust=0.75,hjust=0.5),
  plot.margin = margin(-0.25,0.25,-0.25,0.05,"cm"),
  legend.key.width = unit(0.3,"cm"))
```

# All Plots
```{r}
Blank<-ggplot() + theme_void()
#,plot.margin = margin(0.2,0.2,0,0,"cm")

Inset<-ggdraw(Dim + theme_half_open(12)+theme(plot.title = element_blank(),axis.ticks = element_blank(),axis.text = element_blank(),legend.position = "none")) +
  draw_plot(Highlight, .7, .2, .3, .3) +
  draw_plot_label(
    c("B"),
    c(0.75),
    c(0.35),
    size = 12)

Top<-plot_grid(Inset,OntoPlot,nrow=1,rel_widths = c(2,3),labels=c("A","C"))
Bottom<-plot_grid(BC1,Blank,nrow=1,rel_widths = c(1,1),labels=c("D","E"))
Full<-plot_grid(Top,Bottom,nrow=2,rel_heights = c(1,1))

ggsave("Proposal-MicrogliaDEG.png",width = 8.5,height = 8.5,units = "in",bg="white")
```
