---
title: "Figure 2"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---
# Figure 3 - Microglia Clustering and DAM

```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(reshape2)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(gridExtra)
library(here)
library(RColorBrewer)
library(sjmisc)
library(ggrepel)
library(viridis)
library(ComplexHeatmap)
setwd("F:/Data/Sequencing/SavedData")
#setwd("/Users/alinakline-schoder/Documents/Github.nosync/Data")
load("7-CAMFigure.RData")
load("3-AllCells.RData")
Integrated$Treatment<-factor(Integrated$Treatment,levels=c("Naive","Sham","1d BBBO","3d BBBO"))
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
CAM$clusters_labeled<-recode(CAM$seurat_clusters,
                     "1"="H2-Ab1+",
                     "2"="Mrc1+",
                     "0"="Ccl2+")
ColorsTreatment<-c("#FFFFFF","#A3A3A3","#75A0B2","#205F83")
names(ColorsTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
LinesTreatment<-c("#A3A3A3",ColorsTreatment[2:4])
names(LinesTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
ColorMacrophageClusters<-c("#e07a5f","#3d405b","#81b29a")
names(ColorMacrophageClusters)<-levels(CAM$clusters_labeled)
library(circlize)
Colors_Feat<-colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))
CAM$Phase<-factor(CAM$Phase,levels = c("G0","G1S","S","G2M","M","MG1"))
ColorsAllClusters[!str_contains("CAM",levels(Integrated$cluster_full),switch = T)]<-"gray"
ColorsAllClusters[str_contains("CAM",levels(Integrated$cluster_full),switch = T)]<-"red"
```

# Clusters UMAP
```{r}
Dim1<-DimPlot(CAM,group.by = "clusters_labeled",label=FALSE,cols = ColorMacrophageClusters)+theme(plot.title = element_blank(),
                                                                                                                 axis.ticks = element_blank(),
                                                                                                                 axis.text = element_blank(),
                                                                                                                 legend.text = element_text(size=8),
        legend.key.size = unit(0.1,"mm"),
        legend.spacing = unit(0,"mm"),
        legend.position = c(0.3,1))+guides(color=guide_legend(override.aes = list(size=4),nrow=1))+scale_y_continuous(limits=c(-6.5,5))+scale_x_continuous(limits=c(-5,7))
```


# Heatmap
```{r}
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))
Idents(CAM)<-"Treatment"
Genes2Plot<-CAM_Treatment_Markers%>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC)
Sub<-subset(CAM,downsample=200)
Data<-t(Sub@assays$SCT@data[unique(Genes2Plot$gene),])
Data<-cbind(as.data.frame(Data),Sub$clusters_labeled,Sub$Treatment)
colnames(Data)[dim(Data)[2]-1]<-"Cluster"
colnames(Data)[dim(Data)[2]]<-"Treatment"
Data<-Data[order(Data$Treatment,Data$Cluster),]
Treatment<-Data$Treatment
Cluster<-Data$Cluster
Data<-Data[,1:(dim(Data)[2]-2)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(ColorsTreatment)<-levels(CAM$Treatment)
Top<-columnAnnotation(Treatment=anno_simple(Treatment,height = unit(4, "mm"),col = ColorsTreatment,border = TRUE), Cluster=anno_simple(Cluster,height=unit(2,"mm"),col=ColorMacrophageClusters),show_legend=FALSE,show_annotation_name=FALSE)
HM<-Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            show_column_names = FALSE,
            row_names_side = "left",
            top_annotation = Top,
            col=col_fun,
            show_heatmap_legend = FALSE,
            row_names_gp = gpar(fontsize=6),
            column_split = Treatment,
            column_title_gp = gpar(fontsize=8))
HMLeg<-grid.grabExpr(draw(Legend(col_fun = col_fun, 
                                  direction = "vertical",
                                  grid_height = unit(0.5,"mm"),
                                  grid_width=unit(1,"mm"),
                                  at=c(-2,0,2),
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=6),
                                  title_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  labels = c("-2", "0", "2"))))
HM_Ready<-plot_grid(grid.grabExpr(draw(HM)),HMLeg,rel_widths = c(10,1),nrow=1)
```

# Volcano plots
```{r}
toptable <- as.data.frame(Markers_1d)
toptable$lab <- rownames(Markers_1d)
Genes<-c("Ccl2","Ccl4","Fos","Il1b","Pf4","Ccl12","Malat1")
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))
Volcano24<-ggplot(toptable, aes(x = xvals, y = yvals)) + geom_point(na.rm = TRUE,size=0.1,fill=unname(ColorsTreatment[3]))+ labs(title = '1d BBBO v Sham')+xlab(xlab) + ylab(ylab) + geom_label_repel(aes(label=lab),size=3,label.padding = unit(0.1, "lines"))+theme(
  panel.grid = element_blank(),
  plot.title = element_text(size=10),
  plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
  panel.background = element_blank(),
  axis.line = element_line(size=0.1),
  axis.text = element_text(size=8),
  axis.title = element_text(size=10))+scale_y_continuous(expand=c(0,0))




toptable <- as.data.frame(Markers_3d)
toptable$lab <- rownames(Markers_3d)
Genes<-c("Malat1","Pf4","Lgals3","Ifitm3","Fos","Mrc1","Vim")
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))
Volcano72<-ggplot(toptable, aes(x = xvals, y = yvals)) + geom_point(na.rm = TRUE,size=0.1,fill=unname(ColorsTreatment[4]))+ labs(title = '3d BBBO v Sham')+xlab(xlab) + ylab(ylab) + geom_label_repel(aes(label=lab),size=3,label.padding = unit(0.1, "lines"))+theme(
  panel.grid = element_blank(),
  plot.title = element_text(size=10),
  plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
  panel.background = element_blank(),
  axis.line = element_line(size=0.1),
  axis.text = element_text(size=8),
  axis.title = element_text(size=10))+scale_y_continuous(expand=c(0,0))
```

# bar charts
```{r}
tab<-as.data.frame(table(CAM$Treatment,CAM$Phase))
tot<-as.data.frame(table(CAM$Treatment))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
BC3<-ggplot(tab,aes(x=Var2,y=Var1,fill=Freq_Norm))+geom_tile()+scale_fill_gradientn(colours = c("white","black"),limits = c(0,100),breaks=c(0,100),guide=guide_colorbar(title.position = "right",title = "Frequency (%)",label.position="right"))+geom_tile(aes(y=Var1,x=0.5),width=0.166,fill=ColorsTreatment[tab$Var1],color=LinesTreatment[tab$Var1])+scale_y_discrete(expand=c(0,0))+theme_minimal()+scale_y_discrete(expand=c(0,0))+scale_x_discrete(expand=c(0,0))+theme(legend.position = "right")+xlab("Assigned Phase")+
  theme(legend.key.width = unit(0.2,"cm"),
        legend.title = element_text(size=7,hjust=0.5,vjust=-4,angle=-90),
        legend.text = element_text(size=6),
        axis.text = element_text(size=6),
        axis.title.x = element_text(size=8),
        legend.box.margin = margin(0,0,-0.5,-0.25,"cm"),
        axis.text.x = element_text(size=6,vjust=0.75,hjust=0.5),
        axis.title.y = element_blank(),
        plot.margin = margin(0.25,0.25,0.5,0.5,"cm"),
        legend.key.height = unit(0.5,"cm"))
```


# ontology
```{r}
Terms<-c("cytokine activity",
         "response to chemokine",
         "extracellular exosome",
         "macrophage migration",
         "defense response",
         "innate immune response",
         "inflammatory response",
         "endosome",
         "macrophage activation",
         "cell migration")
Onto_1d$Time<-"1d"
Onto_3d$Time<-"3d"
Onto_All<-rbind(Onto_1d,Onto_3d)
OntoPlotdata<-Onto_All[Onto_All$Term %in% Terms,]
OntoPlotdata$Time<-as.factor(OntoPlotdata$Time)
KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(italic(P[Fis]))
library(scales) 
OntoPlotdata$Group<-recode(OntoPlotdata$Group,"Biological Process"="BP",
                           "Cellular Component"="CC",
                           "Molecular Function"="MF")
OntoPlot<-ggplot(OntoPlotdata,aes(x=Time,y=Term,color=-log(PVal_KS),size=PCT))+
  facet_grid(Group~.,scales = "free",space = "free")+
  geom_point()+
  theme_minimal()+scale_color_viridis()+scale_color_viridis(guide=guide_colorbar(title=KSLab,title.position = "top"))+ scale_size_continuous(guide=guide_legend(title="Genes (%)",title.position = "top"),breaks = c(10,35,60),limits=c(10,60),range = c(0.5,4))+
  theme(legend.position = "top",
        axis.text.y = element_text(size=6),
        legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.key.height = unit(2,"mm"),
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        plot.margin = margin(0.5,0.5,0.5,0.5,"cm"),
        axis.title = element_blank(),
        legend.spacing.x = unit(0,"cm"),
        legend.box.spacing = margin(-0.5,0.5,0.25,0,"cm"),
        legend.text = element_text(size=6),
        legend.title = element_text(size=8),
        strip.text.y = element_text(size=10))

```

# Highlighting on Integrated UMAP
```{r}
Idents(Integrated)<-"cluster_full"
Highlight<-DimPlot(Integrated,group.by = "cluster_full",cols=ColorsAllClusters,label=FALSE)+NoLegend()+
  theme(plot.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        
        panel.spacing = unit(0,"cm"),
        panel.border = element_rect(color="black"))

```

# Pie chart
```{r}
tab<-as.data.frame(table(Integrated$Treatment,Integrated$cell_type))
tot<-as.data.frame(table(Integrated$Treatment))
rownames(tot)<-tot$Var1
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq
tab<-tab[tab$Var2=="CAM",]
Pie<-ggplot(tab,aes(x=Var1,y=Freq_Norm*100,fill=Var1,color=Var1))+stat_summary(fun="mean",geom="bar")+scale_fill_manual(values=ColorsTreatment)+scale_color_manual(values=LinesTreatment)+theme(legend.position="none")+scale_y_continuous(limits = c(0,0.65),breaks = c(0,0.25,0.5),labels=c("0%","25%","50%"),expand = c(0,0),position = "right")+theme(legend.position="none",
        plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line = element_line(size=0.1),
        axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        axis.title.x = element_blank(),
        panel.grid = element_blank()) + scale_y_continuous(expand = c(0,0)) + 
  ylab("CAM (% of Total Cells)") + 
  xlab("Treatment")
```


# Putting it all together
```{r}
Inset<-ggdraw(Dim1 + theme_half_open(12) + theme(plot.title = element_blank(),axis.ticks = element_blank(),axis.text = element_blank(),legend.position = c(0,0.1))) +
  draw_plot(Highlight, .7, .7, .3, .3) +
  draw_plot_label(
    c("B"),
    c(0.75),
    c(0.985),
    size = 12)
Top<-plot_grid(Inset,plot_grid(Pie,BC3,nrow=1,align = "h",labels = c("C","D"),axis="tb"),rel_widths = c(1,2),labels = c("A",""))
Volcanos<-plot_grid(Volcano24,Volcano72,nrow = 1,labels = c("G","H"))
A<-plot_grid(HM_Ready,plot_grid(Volcanos,OntoPlot,nrow=2,labels = c("","I")),nrow=1,labels = c("E"))
Full<-plot_grid(Top,A,nrow=2,rel_heights = c(1,2))
ggsave("Proposal-CAM.png",width = 8.5,height = 6,units = "in",bg="white")

Volcanos<-plot_grid(Volcano24,Volcano72,nrow = 1,labels = c("A","B"))
A<-plot_grid(Volcanos,OntoPlot+theme(legend.position = "bottom",axis.text.y=element_text(size=10)),nrow=2,labels = c("","C"),rel_heights = c(1,1.25))
ggsave("Proposal-PPT-CAMDEG.png",width = 4,height = 5,units = "in",bg="white")

Pie+theme(axis.text=element_text(size=8),axis.title = element_text(size=12))
ggsave("Proposal-PPT-CAMPer.png",width = 3,height = 3,units = "in",bg="white")
```

