---
title: "All Cells"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---


```{r message = FALSE, echo = FALSE}
rm(list = ls())
#Sys.setenv(JAVA_HOME = "C:/Program Files (x86)/Java/jdk1.8.0_311/")
library(cowplot)
library(Seurat)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(reshape2)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(gridExtra)
library(ComplexHeatmap)
library(RColorBrewer)
library(UpSetR)
library(tidyverse)
library(rJava)
library(venneuler)
library(grid)
library(ggVennDiagram)
#library(gridGraphcs)

ColorsTreatment<-c("#BD6B73","#CCAD8F","#81C3D7","#16425B")
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
setwd("F:/Data/Sequencing/SavedData/2021_12_PLXSonications")
CavitationDose<-read.csv('CavitationDose-Table 1.csv')
MRIs<-read.csv('MRISize-MRIs.csv')
Info<-read.csv('TreatmentMice-Table 1.csv')
rownames(Info)<-Info$Mouse.Name
```
```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(rstatix)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(cowplot)

GraphPadTheme<-theme_bw()+theme(panel.grid = element_blank(),panel.border = element_blank(),axis.line = element_line(size=0.5))
```




```{r}
library(dplyr)


#Info<-Info[Info$Feed!="Repopulating",]
CustomColors<-c("#a8a8a8","#986fb5")
CavitationDose$Group<-Info[CavitationDose$Mouse,]$Feed

MRIs$Day.0.Norm<-MRIs$Day.0/MRIs$Day.0
MRIs$Day.1.Norm<-MRIs$Day.1/MRIs$Day.0
MRIs$Day.2.Norm<-MRIs$Day.2/MRIs$Day.0
MRIs$Day.3.Norm<-MRIs$Day.3/MRIs$Day.0
MRIs$Day.4.Norm<-MRIs$Day.4/MRIs$Day.0
MRIs$Day.5.Norm<-MRIs$Day.5/MRIs$Day.0
MRIs$Group<-Info[MRIs$Mouse,]$Feed
MRIs$Feed<-recode(MRIs$Group,
                   "Repopulating"="Depletion")
MRI0<-ggplot(MRIs,aes(x=Feed,y=Day.0,fill=Feed))+geom_boxplot(color="black",aes(fill=Feed),outlier.colour = NA,outlier.fill = NA)+geom_dotplot(binaxis='y', stackdir='center',dotsize=0.5,fill="black",color="black")+stat_compare_means(method="t.test",label="p.format",label.x.npc = 0.4,label.y.npc = 0.85,size=3)+ylab(bquote('Day 0 BBBO Volume '(mm^3)))+scale_fill_manual(values=CustomColors)+theme_bw()+theme(legend.position = "none")+theme(axis.title = element_text(size=8),plot.margin = margin(0.25,0.25,0.25,0.5,"cm"))+scale_y_continuous(limits=c(0,40),expand = c(0,0))



# Removing repopulating
MRIs<-MRIs[MRIs$Group!="Repopulating",]
MRIs_Long<-pivot_longer(MRIs,cols = c("Day.1.Norm","Day.2.Norm","Day.3.Norm","Day.4.Norm","Day.5.Norm"))
MRIs_Long$name<-recode(MRIs_Long$name,
                       "Day.1.Norm"="Day 1",
                       "Day.2.Norm"="Day 2",
                       "Day.3.Norm"="Day 3",
                       "Day.4.Norm"="Day 4",
                       "Day.5.Norm"="Day 5")
MRIs_Long$Group<-factor(MRIs_Long$Group,levels=c("Control","Depletion"))
A1<-ggplot(MRIs_Long,aes(x=name,y=value,color=Group,fill=Group))+geom_boxplot(color="black",aes(fill=Group),outlier.colour = NA,outlier.fill = NA)+
  geom_dotplot(binaxis='y', stackdir='center',dotsize=0.5,position=position_dodge(width=0.75),color="black")+
  stat_compare_means(method="t.test",size=3,label="p.format",show.legend = FALSE)+
  scale_fill_manual(values=CustomColors)+
  scale_color_manual(values=CustomColors)+theme_bw()+ylab("Opening Volume (Relative to Day 0)")+xlab("Days after treatment")+theme(legend.position = c(0.85,0.8),legend.box.background = element_rect(color="black",linetype = "solid",fill="white"),legend.background = element_blank(),legend.title = element_blank())



MRIs<-MRIs[MRIs$Group!="Repopulating",]
MRIs_Long<-pivot_longer(MRIs,cols = c("Day.1","Day.2","Day.3","Day.4","Day.5"))
A2<-ggplot(MRIs_Long,aes(x=name,y=value,color=Group))+geom_boxplot(color="black",aes(fill=Group),outlier.colour = NA,outlier.fill = NA)+geom_dotplot(binaxis='y', stackdir='center',dotsize=0.5,fill="black",color="black")+stat_compare_means(method="t.test",size=3,label="p.format",show.legend = FALSE)+scale_color_manual(values=CustomColors)+theme_bw()+ylab("Opening Volume (Relative to Day 0)")+xlab("Days after treatment")+theme(legend.position = c(0.85,0.8),legend.box.background = element_rect(color="black",linetype = "solid",fill="white"),legend.background = element_blank(),legend.title = element_blank())




# Day 0
Info<-Info[!is.na(Info$Days.Open),]
Info_New<-Info[Info$Feed!="Repopulating",]
C<-ggplot(Info_New,aes(x=Feed,y=Days.Open,color=Feed,fill=Feed))+geom_boxplot(color="black")+geom_dotplot(binaxis='y', stackdir='center',dotsize=0.5,fill="black",color="black",outlier.colour = NA,outlier.fill = NA)+scale_fill_manual(values=CustomColors)+scale_color_manual(values=CustomColors)+theme_bw()+stat_compare_means(method="t.test",label="p.format",label.x.npc = 0.4,label.y.npc = 0.85,size=3)+ylab("Duration of BBB Opening (Days)")+theme(legend.position="none")+scale_y_continuous(limits = c(0,8),expand = c(0,0))+theme(axis.title= element_text(size=8),plot.margin = margin(0.25,0.25,0.25,0.5,"cm"))
```

# Putting it together
```{r}
Placeholder<-ggplot()+geom_blank()+theme_void()
Top<-plot_grid(Placeholder,Placeholder,Placeholder,nrow=1,labels=c("a","b","c"),rel_widths = c(2,1,1))

BCs<-plot_grid(MRI0,C,nrow=1,align="h",labels=c("f","g"))
Right<-plot_grid(Placeholder,BCs,nrow=2,labels=c("e"))
Bottom<-plot_grid(A1,Right,nrow=1,labels=c("d"))
Full<-plot_grid(Top,Bottom,nrow=2,rel_heights = c(1,2))
ggsave("Figure6-PLX.png",width = 8.5,height = 7.0,units = "in",plot = Full,bg = "white")
```

