---
title: "Figure 3: DAM"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---
# Setup

## Loading libraries and data
```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
library(BiocManager)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(circlize)
library(ggrepel)


ColorsTreatment<-c("#FFFFFF","#A3A3A3","#75A0B2","#205F83")
names(ColorsTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
LinesTreatment<-c("#A3A3A3",ColorsTreatment[2:4])
names(LinesTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
#load("/Users/alinakline-schoder/Documents/SavedData/3-AllCells.RData")
load("/Users/alinakline-schoder/Documents/SavedData/5-MicrogliaFigures.RData")

col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))

MicrogliaClusterColors<-c("#4FB3AA","#E9D8A6","#CA6702","#057985","#AE2012", "#BFD5B2","#0A9396", "#FFE987", "#F7C244", "#F4E197", "#D56D02","#BB3E03","#94D2BD")
names(MicrogliaClusterColors)<-levels(Microglia$seurat_clusters)
MicrogliaClusterColors[levels(Microglia$seurat_clusters)!="2"]<-"gray"
#ColorsAllClusters[str_contains("Microglia",levels(Integrated$cluster_full),switch = T)]<-"red"
```
## Setting themes
```{r}
ThemeAll<-theme(legend.position = "none",
                panel.grid = element_blank(),
                axis.text = element_text(size=8),
                axis.title = element_text(size=10),
                plot.margin = margin(0.5,0.5,0.25,0.25,"cm"),
                strip.text=element_text(size=10),
                axis.line = element_line(size=0.5,color="black"),
                plot.title = element_blank(),
                panel.background = element_blank())

ThemeLeg<-theme(legend.position = "right",
        legend.direction = "vertical",
        legend.box = "vertical",
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        legend.box.spacing = margin(-0.5,0.5,0.25,0,"cm"),
        legend.text = element_text(size=8),
        legend.title = element_text(size=8))

ThemeOnto<-ThemeAll+ThemeLeg+theme(axis.title = element_blank(),axis.line = element_blank())
        
ThemeUMAP<-ThemeAll+theme(axis.ticks = element_blank(),
                 axis.text = element_blank())
ThemeVolcano<-ThemeAll

ThemeBoxPlot<-ThemeAll+theme(axis.title.x = element_blank())
```

# Highlighting DAM on microglia UMAP
```{r}
Dim1<-DimPlot(Microglia,group.by = "seurat_clusters",label=FALSE,cols =MicrogliaClusterColors)+scale_y_continuous(limits=c(-9.5,7))+scale_x_continuous(limits=c(-4.5,7.2))+ThemeUMAP
```

# DAM marker volcano 
```{r}
toptable <- as.data.frame(DAMMarkers)
toptable$lab <- rownames(DAMMarkers)
Genes<-c("Cd9","Lpl","Spp1","Apoe","Tmem119","P2ry12","Cd63","Cx3cr1")
toptable$color<-MicrogliaClusterColors[3]
toptable[toptable$p_val_adj>0.05,]$color<-"black"
toptable[abs(toptable$avg_log2FC)<0.5,]$color<-"black"
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "FC")
ylab<-bquote(~-Log[10] ~ italic(P))

DAMVolc<-ggplot(toptable, aes(x = xvals, y = yvals)) + 
  geom_point(na.rm = TRUE,size=0.1,color=toptable$color) + 
  geom_label_repel(aes(label=lab),size=3,label.padding = unit(0.1, "lines"),max.overlaps = 100) + scale_y_continuous(expand=c(0,0))+xlab(xlab) + ylab(ylab)+ThemeVolcano
```

# percentage of microglia that are DAM
```{r}
tab<-as.data.frame(table(Microglia$orig.ident,Microglia$Treatment,Microglia$seurat_clusters))
tab<-tab[tab$Var3=="2",]
Tota<-as.data.frame(table(Microglia$orig.ident,Microglia$Treatment))
Tota$Full<-paste(Tota$Var1,Tota$Var2)
tab$Full<-paste(tab$Var1,tab$Var2)
rownames(Tota)<-Tota$Full
tab$Total<-Tota[tab$Full,]$Freq
tab<-tab[tab$Total>0,]
tab$Freq_Adj<-tab$Freq/tab$Total

tab$Var2<-recode(tab$Var2,
                 "1d BBBO"="1d","3d BBBO"="3d")
names(ColorsTreatment)<-levels(tab$Var2)
Percent<-ggplot(tab,aes(x=Var2,y=Freq_Adj*100))+geom_boxplot(color="black",aes(fill=Var2))+geom_point (color="black")+scale_fill_manual(values=ColorsTreatment)+ scale_y_continuous(expand = c(0,0),limits = c(0,60))+ylab("DAM (% of microglia)")+stat_compare_means(method="anova",size=3,label.y = 50,label="p.format")+ThemeBoxPlot
```


# Heatmap of DEG within DAM
```{r}
library(ComplexHeatmap)
library(viridis)
Idents(Microglia)<-"seurat_clusters"
DAM<-subset(Microglia,idents = "2")
Idents(DAM)<-"Treatment"
marks_1d$pct.dif<-marks_1d$pct.1-marks_1d$pct.2
marks_3d$pct.dif<-marks_3d$pct.1-marks_3d$pct.2

Genes2Plot1<-marks_1d%>%
    top_n(n = 10, wt = pct.dif)

Genes2Plot2<-marks_3d%>%
    top_n(n = 10, wt = pct.dif)

col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "orange"))
Genes2Plot<-unique(c(rownames(Genes2Plot1),rownames(Genes2Plot2)))
Data<-t(as.matrix(DAM@assays$RNA@data[Genes2Plot,]))
Data<-cbind(as.data.frame(Data),DAM$seurat_clusters,DAM$Treatment)
colnames(Data)[dim(Data)[2]-1]<-"Cluster"
colnames(Data)[dim(Data)[2]]<-"Treatment"
Data<-Data[order(Data$Treatment,Data$Cluster),]
Treatment<-Data$Treatment
Cluster<-Data$Cluster
Data<-Data[,1:(dim(Data)[2]-2)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(ColorsTreatment)<-levels(Microglia$Treatment)
names(MicrogliaClusterColors)<-levels(Microglia$seurat_clusters)
Top<-columnAnnotation(Treatment=anno_simple(Treatment,height = unit(2, "mm"),col = ColorsTreatment,border = TRUE), Cluster=anno_simple(Cluster,height=unit(1,"mm"),col=MicrogliaClusterColors),show_legend=FALSE,show_annotation_name=FALSE)
HM<-Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            show_column_names = FALSE,
            row_names_side = "left",
            width=unit(4,"cm"),
            top_annotation = HeatmapAnnotation(label = anno_block(height=unit(0.5,"cm"),gp = gpar(fill = ColorsTreatment),
labels = c("", "Sham", "1d","3d"), labels_gp = gpar(fontsize=8,col = c("black","white","white","white"))),show_annotation_name = F),
            col=col_fun,
            show_heatmap_legend = FALSE,
            row_names_gp = gpar(fontsize=8),
            column_split = Treatment, column_title = NULL)
HMLeg<-grid.grabExpr(draw(Legend(col_fun = col_fun, 
                                  direction = "horizontal",
                                 title_position = "topcenter",
                                 title="Normalized Expression",
                                  grid_height = unit(0.5,"mm"),
                                  grid_width=unit(1,"mm"),
                                  at=c(-2,0,2),
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  title_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  rot = 90,
                                                  fontsize=8),
                                  labels = c("-2", "0", "2"))))
HM_ReadyGenes<-plot_grid(grid.grabExpr(draw(HM)),HMLeg,rel_heights = c(10,1),nrow=2)
```

# Ontology searches
```{r}
Terms<-c("glial cell development",
         "gliogenesis",
         "macrophage migration",
         "phagocytic vesicle",
         "lysosome",
         "response to stimulus",
         "cell chemotaxis",
         "regulation of cell cycle",
         "immune response")
DAM_Onto_1d$Treatment<-"1d"
DAM_Onto_3d$Treatment<-"3d"
All<-rbind(DAM_Onto_1d,DAM_Onto_3d)
OntoPlotdata<-All[All$Term %in% Terms,]
KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(italic(P[Fis]))
library(scales) 
OntoPlot<-ggplot(OntoPlotdata,aes(x=Treatment,y=Term,color=-log(PVal_KS),size=PCT))+
  geom_point()+
  theme_minimal()+scale_color_viridis()+scale_color_viridis(guide=guide_colorbar(title=KSLab,title.position = "top"))+ scale_size_continuous(guide=guide_legend(title="Genes (%)",title.position = "top"),breaks = c(20,40,60),limits=c(20,60),range = c(0.5,4))+ThemeOnto
```


# Putting it all together
```{r}
TopLeft<-plot_grid(Dim1,DAMVolc,nrow=1,labels = c("a","b"),rel_widths = c(1,1),align = "h",axis="tb")
BottomLeft<-plot_grid(Percent,OntoPlot,nrow=1,labels = c("d","e"),align = "h",axis="tb",rel_widths = c(1,1.5))

Full<-plot_grid(plot_grid(TopLeft,BottomLeft,nrow=2),HM_ReadyGenes,nrow=1,rel_widths = c(2,1),labels=c("","c"))
ggsave("Figure3-DAM.png",width = 8,height = 5,units = "in",bg="white")
```

