---
title: "All Cells"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---


```{r message = FALSE, echo = FALSE}
rm(list = ls())
#Sys.setenv(JAVA_HOME = "C:/Program Files (x86)/Java/jdk1.8.0_311/")
library(cowplot)
library(Seurat)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(reshape2)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(gridExtra)
library(ComplexHeatmap)
library(RColorBrewer)
library(UpSetR)
library(tidyverse)
library(rJava)
library(venneuler)
library(grid)
library(ggVennDiagram)
#library(gridGraphcs)

ColorsTreatment<-c("#BD6B73","#CCAD8F","#81C3D7","#16425B")
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
setwd("/Users/alinakline-schoder/Documents/Github.nosync/Data")
load("7-CAMFigure.RData")
load("5-MicrogliaFigures.RData")
load("3-AllCells.RData")

Microglia_1d<-clustermarkers_1d
Microglia_3d<-clustermarkers_3d
CAM_1d<-Markers_1d
CAM_3d<-Markers_3d
```
# Loading Data 4 Venn
```{r}
Microglia_1d_Up<-rownames(Microglia_1d[Microglia_1d$p_val_adj<0.05&Microglia_1d$avg_log2FC>0,])
Microglia_1d_Down<-rownames(Microglia_1d[Microglia_1d$p_val_adj<0.05&Microglia_1d$avg_log2FC<0,])
CAM_1d_Up<-rownames(CAM_1d[CAM_1d$p_val_adj<0.05&CAM_1d$avg_log2FC>0,])
CAM_1d_Down<-rownames(CAM_1d[CAM_1d$p_val_adj<0.05&CAM_1d$avg_log2FC<0,])
Microglia_3d_Up<-rownames(Microglia_3d[Microglia_3d$p_val_adj<0.05&Microglia_3d$avg_log2FC>0,])
Microglia_3d_Down<-rownames(Microglia_3d[Microglia_3d$p_val_adj<0.05&Microglia_3d$avg_log2FC<0,])
CAM_3d_Up<-rownames(CAM_3d[CAM_3d$p_val_adj<0.05&CAM_3d$avg_log2FC>0,])
CAM_3d_Down<-rownames(CAM_3d[CAM_3d$p_val_adj<0.05&CAM_3d$avg_log2FC<0,])

All_Up<-intersect(intersect(Microglia_1d_Up,Microglia_3d_Up),intersect(CAM_1d_Up,CAM_3d_Up))
Just_Microglia_Up<-setdiff(intersect(Microglia_1d_Up,Microglia_3d_Up),c(CAM_1d_Up,CAM_3d_Up))
Just_CAM_Up<-setdiff(intersect(CAM_1d_Up,CAM_3d_Up),c(Microglia_1d_Up,Microglia_3d_Up))
Day1_Only_Up<-setdiff(intersect(CAM_1d_Up,Microglia_1d_Up),c(CAM_3d_Up,Microglia_3d_Up))
Day3_Only_Up<-setdiff(intersect(CAM_3d_Up,Microglia_3d_Up),c(CAM_1d_Up,Microglia_1d_Up))

All_Down<-intersect(intersect(Microglia_1d_Down,Microglia_3d_Down),intersect(CAM_1d_Down,CAM_3d_Down))
Just_Microglia_Down<-setdiff(intersect(Microglia_1d_Down,Microglia_3d_Down),c(CAM_1d_Down,CAM_3d_Down))
Just_CAM_Down<-setdiff(intersect(CAM_1d_Down,CAM_3d_Down),c(Microglia_1d_Down,Microglia_3d_Down))
Day1_Only_Down<-setdiff(intersect(CAM_1d_Down,Microglia_1d_Down),c(CAM_3d_Down,Microglia_3d_Down))
Day3_Only_Down<-setdiff(intersect(CAM_3d_Down,Microglia_3d_Down),c(CAM_1d_Down,Microglia_1d_Down))



```


# Upset plot
```{r}
k<-as.data.frame(list_to_matrix(list(MG_1 = Microglia_1d_Up,
        MG_3 = Microglia_3d_Up,
        CAM_1 = CAM_1d_Up,
        CAM_3 = CAM_3d_Up)))
k$MG_total<-k$MG_1+k$MG_3
k$CAM_total<-k$CAM_1+k$CAM_3
k$Day_1<-k$CAM_1+k$MG_1
k$Day_3<-k$CAM_3+k$MG_3
k$Total<-k$MG_total+k$CAM_total

k<-as.data.frame(list_to_matrix(list(MG_1 = Microglia_1d_Down,
        MG_3 = Microglia_3d_Down,
        CAM_1 = CAM_1d_Down,
        CAM_3 = CAM_3d_Down)))
k$MG_total<-k$MG_1+k$MG_3
k$CAM_total<-k$CAM_1+k$CAM_3
k$Day_1<-k$CAM_1+k$MG_1
k$Day_3<-k$CAM_3+k$MG_3
k$Total<-k$MG_total+k$CAM_total
```




# Venn Diag Up
```{r}
Microglia_1d_Up<-cbind(Microglia_1d_Up,"Microglia_1d_Up")
Microglia_1d_Down<-cbind(Microglia_1d_Down,"Microglia_1d_Down")
CAM_1d_Up<-cbind(CAM_1d_Up,"CAM_1d_Up")
CAM_1d_Down<-cbind(CAM_1d_Down,"CAM_1d_Down")
Microglia_3d_Up<-cbind(Microglia_3d_Up,"Microglia_3d_Up")
Microglia_3d_Down<-cbind(Microglia_3d_Down,"Microglia_3d_Down")
CAM_3d_Up<-cbind(CAM_3d_Up,"CAM_3d_Up")
CAM_3d_Down<-cbind(CAM_3d_Down,"CAM_3d_Down")
tab<-rbind(Microglia_1d_Up,Microglia_3d_Up,CAM_1d_Up,CAM_3d_Up)
colnames(tab)<-c("Gene","Treatment")
v2 <- venneuler(data.frame(tab))
#v2$labels<-NA
v2$centers[,"x"]<-(v2$centers[,"x"]-0.5)*-1+0.5

 plot(v2, cex.main = 1)
  text(labels = "1d Microglia",x=0.075,y=0.7,xpd=NA)
  text(labels = "3d Microglia",x=0.125,y=0.3,xpd=NA)
  text(labels = "1d CAM",x=0.775,y=0.55,xpd=NA)
  text(labels = "3d CAM",x=0.8,y=0.4,xpd=NA)
  title("Up-Regulated Genes") 
  
  
dev.copy(png,"Figure5-VennUp.png", width=800, height=800,res=200)
```

```{r}
tab<-rbind(Microglia_1d_Down,Microglia_3d_Down,CAM_1d_Down,CAM_3d_Down)
colnames(tab)<-c("Gene","Treatment")
v1 <- venneuler(data.frame(tab))
v1$labels<-NA
v1$centers[,"y"]<-(v1$centers[,"y"]-0.5)*-1+0.5
  
plot(v1, cex.main = 1)
  text(labels = "1d Microglia",x=0.15,y=0.65,xpd=NA)
  text(labels = "3d Microglia",x=0.2,y=0.3,xpd=NA)
  text(labels = "1d CAM",x=0.85,y=0.6,xpd=NA)
  text(labels = "3d CAM",x=0.85,y=0.25,xpd=NA)
  title("Down-Regulated Genes")
dev.copy(png,"Figure5-VennDown.png", width=800, height=800,res=200)

```



```{r}
Blank<-ggplot() + theme_void()

plot_grid(Blank,plot_grid(Blank,Blank,nrow=1,labels = c("b","c")),labels = c("a",""),nrow=2)
ggsave("Figure5.png",width = 7.5,height = 5)
```

