---
title: "Figure Sham"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---
# Supplemental Figure - Sham

```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(reshape2)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(gridExtra)
library(here)
library(circlize)
library(sjmisc)
library(ggrepel)
#setwd("F:/Data/Sequencing/SavedData")
alltreat<-c("Naive","1d MB Sham","1d FUS Sham","1d BBBO","3d MB Sham","3d FUS Sham","3d BBBO")
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
ColorsTreatment<-c("#FFFFFF","#A3A3A3","#A3A3A3","#75A0B2","#A3A3A3","#A3A3A3","#205F83")
names(ColorsTreatment)<-alltreat
LinesTreatment<-c("#A3A3A3",ColorsTreatment[2:7])
names(LinesTreatment)<-alltreat
setwd("F:/Data/Sequencing/SavedData")
#setwd("/Users/alinakline-schoder/Documents/Github.nosync/Data")
load("7-CAMFigure.RData")
load("3-AllCells.RData")
load("5-MicrogliaFigures.RData")
Idents(Microglia)<-"Treatment_Specific"
Microglia$Treatment_Specific<-factor(Microglia$Treatment_Specific,levels=alltreat)
Integrated$Treatment_Specific<-factor(Integrated$Treatment_Specific,levels=alltreat)
Mark_Shams<-FindAllMarkers(Microglia,only.pos = T)
MicrogliaClusterColors<-c("#4FB3AA","#E9D8A6","#CA6702","#057985","#AE2012", "#BFD5B2","#0A9396", "#FFE987", "#F7C244", "#F4E197", "#D56D02","#BB3E03","#94D2BD")
```

# Microglia Heatmap
```{r}
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))
Mark_Shams$pct.dif<-Mark_Shams$pct.1-Mark_Shams$pct.2
Mark_Shams<-Mark_Shams[Mark_Shams$cluster!="1d BBBO",]
Mark_Shams<-Mark_Shams[Mark_Shams$cluster!="3d BBBO",]
Mark_Shams<-Mark_Shams[Mark_Shams$cluster!="Naive",]

Genes2Plot<-Mark_Shams%>%
    group_by(cluster) %>%
    top_n(n = 15, wt = pct.dif)
Genes2Plot<-unique(Genes2Plot$gene)

Idents(Microglia)<-"Treatment_Specific"
Sub<-subset(Microglia,downsample=500)
Data<-t(as.matrix(Sub@assays$RNA@data[Genes2Plot,]))
Data<-cbind(as.data.frame(Data),Sub$seurat_clusters,Sub$Treatment_Specific)
colnames(Data)[dim(Data)[2]-1]<-"Cluster"
colnames(Data)[dim(Data)[2]]<-"Treatment_Specific"
Data<-Data[order(Data$Treatment_Specific,Data$Cluster),]
Treatment<-Data$Treatment_Specific
Cluster<-Data$Cluster
Data<-Data[,1:(dim(Data)[2]-2)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(MicrogliaClusterColors)<-levels(Microglia$seurat_clusters)
Top<-columnAnnotation(Treatment=anno_simple(Treatment,height = unit(2, "mm"),col = ColorsTreatment,border = TRUE), Cluster=anno_simple(Cluster,height=unit(2,"mm"),col=MicrogliaClusterColors),show_legend=FALSE,show_annotation_name=FALSE)
HM<-Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            show_column_names = FALSE,
            row_names_side = "left",
            top_annotation = Top,
            col=col_fun,
            show_heatmap_legend = FALSE,
            row_names_gp = gpar(fontsize=6,family="Arial"),
            column_split = Treatment,
            column_title_gp = gpar(fontsize=6,family="Arial"))
HMLeg<-grid.grabExpr(draw(Legend(col_fun = col_fun, 
                                  direction = "vertical",
                                  grid_height = unit(0.5,"mm"),
                                  grid_width=unit(1,"mm"),
                                  at=c(-2,0,2),
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=6),
                                  title_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  labels = c("-2", "0", "2"))))
HM<-plot_grid(grid.grabExpr(draw(HM)),HMLeg,rel_widths = c(10,1),nrow=1)
```

# microglia cluster distribution 
```{r}
tab<-as.data.frame(table(Microglia$Treatment_Specific,Microglia$seurat_clusters))
tot<-as.data.frame(table(Microglia$Treatment_Specific))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
BC2<-ggplot(tab,aes(y=Var1,x=Var2,fill=Freq_Norm))+geom_tile()+scale_fill_gradientn(colours = c("white","black"),limits = c(0,100),breaks=c(0,100),guide=guide_colorbar(title.position = "right",title = "Frequency (%)",label.position="right"))+geom_tile(aes(y=0.5,x=Var2),height=0.05,fill=MicrogliaClusterColors[tab$Var2])+scale_y_discrete(expand=c(0,0))+geom_tile(aes(y=Var1,x=0.5),width=0.25,fill=ColorsTreatment[tab$Var1],color=LinesTreatment[tab$Var1])+theme_minimal()+scale_y_discrete(expand=c(0,0))+scale_x_discrete(expand=c(0,0))+theme(legend.position = "right")+xlab("Cluster")+theme(legend.key.width = unit(0.2,"cm"),legend.title = element_text(size=8,angle=-90,hjust=0.5,vjust=-5),legend.text = element_text(size=6),axis.text = element_text(size=6),axis.title.x = element_text(size=8),legend.box.margin = margin(0,-0.5,0,-0.25,"cm"),axis.text.x = element_text(size=6),axis.title.y = element_blank())+xlab("Cluster")
```

# microglia phase distribution
```{r}
tab<-as.data.frame(table(Microglia$Treatment_Specific,Microglia$Phase))
tot<-as.data.frame(table(Microglia$Treatment_Specific))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
BC1<-ggplot(tab,aes(y=Var1,x=Var2,fill=Freq_Norm))+geom_tile()+scale_fill_gradientn(colours = c("white","black"),limits = c(0,100),breaks=c(0,100),guide=guide_colorbar(title.position = "right",title = "Frequency (%)",label.position="right"))+geom_tile(aes(y=Var1,x=0.5),width=0.05,fill=ColorsTreatment[tab$Var1],color=LinesTreatment[tab$Var2])+theme_minimal()+scale_y_discrete(expand=c(0,0))+scale_x_discrete(expand=c(0,0))+theme(legend.position = "right")+theme(legend.position = "right")+xlab("Cluster")+theme(legend.key.width = unit(0.2,"cm"),legend.title = element_text(size=8,angle=-90,hjust=0.5,vjust=-5),legend.text = element_text(size=6),axis.text = element_text(size=6),axis.title.x = element_text(size=8),legend.box.margin = margin(0,-0.5,0,-0.25,"cm"),axis.text.x = element_text(size=6),axis.title.y = element_blank())+xlab("Phase")
```

# CAM % plot
```{r}
tab<-as.data.frame(table(Integrated$Treatment_Specific,Integrated$cell_type))
tot<-as.data.frame(table(Integrated$Treatment_Specific))
rownames(tot)<-tot$Var1
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq
tab<-tab[tab$Var2=="CAM",]
Pie<-ggplot(tab,aes(y=Var1,x=Freq_Norm,fill=Var1,color=Var1))+stat_summary(fun="mean",geom="bar")+scale_fill_manual(values=ColorsTreatment)+scale_color_manual(values=LinesTreatment)+theme(legend.position="none")+scale_x_continuous(limits = c(0,0.65),breaks = c(0,0.25,0.5),labels=c("0%","25%","50%"),expand = c(0,0),position = "bottom")+theme_minimal()+theme(legend.position = "none")+ylab("Treatment")+xlab("Cluster")+theme(legend.key.width = unit(0.2,"cm"),legend.title = element_text(size=8,angle=-90,hjust=0.5,vjust=-5),legend.text = element_text(size=6),axis.text = element_text(size=6),axis.title.x = element_text(size=8),legend.box.margin = margin(0,-0.5,0,-0.25,"cm"),axis.text.x = element_text(size=6),axis.title.y = element_blank())+xlab("CAM (%)")
```


# Putting it all together
```{r}
Pie
BC1
BC2
HM

Full<-plot_grid(HM,plot_grid(nrow=3,BC1,BC2,Pie,align = "v",axis = "lr",labels=c("b","c","d")),nrow=1,labels = c("a",""),rel_widths = c(2,1))
ggsave("FigureSupp-Sham.png",width = 8.5,height = 6.5,units = "in",bg="white")

```

