---
title: "Microglia Figure"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---

# Setting up
## loading everything
```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
library(BiocManager)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(ComplexHeatmap)
library(RColorBrewer)
library(circlize)
library(sjmisc)
library(viridis)
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
ColorsTreatment<-c("#FFFFFF","#A3A3A3","#75A0B2","#205F83")
LinesTreatment<-c("#A3A3A3",ColorsTreatment[2:4])
names(LinesTreatment)<-c("Naive","Sham","1d FUS-BBBO","3d FUS-BBBO")
load("/Users/alinakline-schoder/Documents/SavedData/3-AllCells.RData")
load("/Users/alinakline-schoder/Documents/SavedData/5-MicrogliaFigures.RData")
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "orange"))
MicrogliaClusterColors<-c("#4FB3AA","#E9D8A6","#CA6702","#057985","#AE2012", "#BFD5B2","#0A9396", "#FFE987", "#F7C244", "#F4E197", "#D56D02","#BB3E03","#94D2BD")

```
## Themes
```{r}
ThemeAll<-theme(legend.position = "none",
                panel.grid = element_blank(),
                axis.text = element_text(size=8),
                axis.title = element_text(size=10),
                plot.margin = margin(0.5,0.5,0.25,0.25,"cm"),
                strip.text=element_text(size=10),
                axis.line = element_line(size=0.5,color="black"),
                plot.title = element_blank(),
                panel.background = element_blank())

ThemeLeg<-theme(legend.position = "right",
        legend.direction = "vertical",
        legend.box = "vertical",
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        legend.box.spacing = margin(-0.5,0.5,0.25,0,"cm"),
        legend.text = element_text(size=8),
        legend.title = element_text(size=8))

ThemeOnto<-theme_minimal()+ThemeAll+ThemeLeg+theme(axis.title = element_blank(),axis.line = element_blank(),panel.background = element_blank())
        
ThemeUMAP<-ThemeAll+theme(axis.ticks = element_blank(),
                 axis.text = element_blank())
ThemeVolcano<-ThemeAll

ThemeBoxPlot<-ThemeAll+theme(axis.title.x = element_blank())
```


# Ontology Plot
```{r}
Onto_1d$Time<-"1d"
Onto_3d$Time<-"3d"
Onto_All<-rbind(Onto_1d,Onto_3d)
BP<-c("phagocytic vesicle",
      "extracellular vesicle",
      "chemokine activity",
      "macrophage chemotaxis",
      "lysosome",
      "microglial cell activation",
      "regulation of immune response",
      "regulation of myeloid cell differentiation",
      "cell cycle",
      "endosome",
      "late endosome",
      "external encapsulating structure",
      "response to interferon-gamma",
      "response to stress",
      "chemokine receptor binding",
      "glial cell migration",
      "gliogenesis")

OntoPlotdata<-Onto_All[Onto_All$Term %in% BP,]
OntoPlotdata$Time<-as.factor(OntoPlotdata$Time)
KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(italic(P[Fis]))
library(scales) 
OntoPlotdata$Group<-recode(OntoPlotdata$Group,"Biological Process"="BP",
                           "Cellular Component"="CC",
                           "Molecular Function"="MF")
OntoPlot<-ggplot(OntoPlotdata,aes(x=Time,y=Term,color=-log(PVal_KS),size=PCT))+
  facet_grid(Group~.,scales = "free",space = "free")+
  geom_point()+scale_color_viridis(guide=guide_colorbar(title=KSLab,title.position = "top"))+ scale_size_continuous(guide=guide_legend(title="Genes (%)",title.position = "top"),breaks = c(25,50,75),limits=c(25,75),range = c(0.5,4))+ThemeOnto
```


# Heatmap for top genes
```{r}
clustermarkers_AllTreatment$pct.dif<-clustermarkers_AllTreatment$pct.1-clustermarkers_AllTreatment$pct.2
Genes2Plot<-clustermarkers_AllTreatment%>%
    group_by(cluster) %>%
    top_n(n = 5, wt = pct.dif)
Genes2Plot<-unique(Genes2Plot$gene)
Idents(Microglia)<-"Treatment"
Sub<-subset(Microglia,downsample=1000)
Data<-t(as.matrix(Sub@assays$RNA@data[Genes2Plot,]))
Data<-cbind(as.data.frame(Data),Sub$seurat_clusters,Sub$Treatment)
colnames(Data)[dim(Data)[2]-1]<-"Cluster"
colnames(Data)[dim(Data)[2]]<-"Treatment"
Data<-Data[order(Data$Treatment,Data$Cluster),]
Treatment<-Data$Treatment
Cluster<-Data$Cluster
Data<-Data[,1:(dim(Data)[2]-2)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(ColorsTreatment)<-levels(Microglia$Treatment)
names(MicrogliaClusterColors)<-levels(Microglia$seurat_clusters)
Top<-columnAnnotation(Treatment=anno_simple(Treatment,height = unit(2, "mm"),col = ColorsTreatment,border = TRUE), Cluster=anno_simple(Cluster,height=unit(1,"mm"),col=MicrogliaClusterColors),show_legend=FALSE,show_annotation_name=FALSE)
HM<-Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            show_column_names = FALSE,
            row_names_side = "left",
            width=unit(6.5,"cm"),
            top_annotation = HeatmapAnnotation(label = anno_block(height=unit(0.5,"cm"),gp = gpar(fill = ColorsTreatment),
labels = c("Naive", "Sham", "1d","3d"), labels_gp = gpar(fontsize=8,col = c("black","white","white","white"))),Cluster=anno_simple(as.character(Cluster),height=unit(1,"mm"),col = MicrogliaClusterColors,border = TRUE),show_annotation_name = F),
            col=col_fun,
            show_heatmap_legend = FALSE,
            row_names_gp = gpar(fontsize=6,family="Arial"),
            column_split = Treatment, column_title = NULL)




HMLeg<-grid.grabExpr(draw(Legend(col_fun = col_fun, 
                                  direction = "vertical",
                                 title_position = "leftcenter-rot",
                                 title="Normalized Expression",
                                  grid_height = unit(0.5,"mm"),
                                  grid_width=unit(1,"mm"),
                                  at=c(-2,0,2),
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  title_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  rot = 90,
                                                  fontsize=8),
                                  labels = c("-2", "0", "2"))))


HM_ReadyGenes<-plot_grid(HMLeg,grid.grabExpr(draw(HM)),rel_widths = c(1,5),nrow=1)
```




# Featureplot
```{r}
DefaultAssay(Microglia)<-"RNA"
Feat<-FeaturePlot(Microglia,features = c("Cx3cr1","Tmem119","Hexb","Cd9","Top2a","Ifitm3"),ncol=3,cols = c("#D3D3D3","orange"))&ThemeUMAP&theme(plot.title=element_text(size=10),axis.title = element_blank())

FeatLeg<-grid.grabExpr(draw(Legend(col_fun = colorRamp2(c(0, 100), c("#D3D3D3","orange")), 
                                  direction = "vertical",
                                 title_position = "leftcenter-rot",
                                 title="Normalized Expression",
                                  grid_height = unit(0.5,"mm"),
                                  grid_width=unit(1,"mm"),
                                  at=c(0,100),
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  title_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  rot = 90,
                                                  fontsize=8),
                                  labels = c("", ""))))

```

# Cluster Distribution Plot
```{r}
tab<-as.data.frame(table(Microglia$Treatment,Microglia$seurat_clusters))
tot<-as.data.frame(table(Microglia$Treatment))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
tab<-tab[,setdiff(colnames(tab),"Freq")]
tab$Var1<-recode(tab$Var1,"1d BBBO"="1d","3d BBBO"="3d")
Dis<-ggplot(tab,aes(x=Var1,y=Freq_Norm,fill=Var2))+geom_bar(position="fill", stat="identity")+scale_fill_manual(values=MicrogliaClusterColors)+ylab("Cluster Size")+ThemeBoxPlot+scale_y_continuous(expand=c(0,0))
```

# Microglia UMAP 
```{r}
Dim<-DimPlot(Microglia,group.by = "seurat_clusters",label=TRUE,cols =MicrogliaClusterColors,label.box = TRUE,label.size = 3)+guides(color=guide_legend(override.aes = list(size=3),ncol=1))+scale_y_continuous(limits=c(-9.5,7))+scale_x_continuous(limits=c(-4.5,7.25)
)+ThemeUMAP
```


# Phase

## Treatment by Phase barplot
```{r}
tab<-as.data.frame(table(Microglia$Treatment,Microglia$Phase))
tot<-as.data.frame(table(Microglia$Treatment))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
tab<-tab[,setdiff(colnames(tab),"Freq")]
tab<-as.data.frame(pivot_wider(tab,names_from = Var2,values_from = Freq_Norm))
rownames(tab)<-tab$Var1
tab<-tab[,setdiff(colnames(tab),"Var1")]

HMPhase2<-Heatmap(as.matrix(tab),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        show_row_names = FALSE,
        show_column_names = TRUE,
        row_names_side = "left",
        col = colorRamp2(c(0, 100), c("white", "black")),
        row_split = c(1:4),
        height = unit(4,"cm"),
        width=unit(4,"cm"),
        column_names_side = "top",
        column_names_centered = T,
        column_names_rot = 0,
        column_names_gp= gpar(fontsize=8,angle=0),
        show_heatmap_legend = FALSE,
        left_annotation = rowAnnotation(label = anno_block(width=unit(0.5,"cm"),gp = gpar(fill = ColorsTreatment),
labels = c("Naive", "Sham", "1d","3d"), labels_gp = gpar(fontsize=8,col = c("black","white","white","white")))), row_title = NULL)

HMLeg1<-grid.grabExpr(draw(Legend(col_fun = colorRamp2(c(0, 100), c("white", "black")), 
                                  direction = "horizontal",
                                 legend_width = unit(2.5,"cm"),
                                  grid_height = unit(1,"mm"),
                                  at=c(0,50,100),
                                 title = "Assigned Phase (%)",
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  title_gp = gpar(col = "black",angle=90,
                                                    
                                                  fontface="plain",
                                                  fontsize=8))))

```

## Phase Score
```{r}
Idents(Microglia)<-"Treatment"
dot_data<-data.frame(Treatment=Microglia$Treatment,G1S=Microglia$G1S.Score,S=Microglia$S.Score,G2M=Microglia$G2M.Score,M=Microglia$M.Score,MG1=Microglia$MG1.Score)

dot_data <- dot_data %>%
  group_by(Treatment) %>%
  summarize(G1S=mean(G1S),S=mean(S),G2M=mean(G2M),M=mean(M),MG1=mean(MG1))
dot_data<-as.data.frame(dot_data)
rownames(dot_data)<-dot_data$Treatment
dot_data<-dot_data[,setdiff(colnames(dot_data),"Treatment")]



HMPhase1<-Heatmap(as.matrix(dot_data),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        show_row_names = FALSE,
        show_column_names = TRUE,
        row_names_side = "left",
        col = col_fun,
        row_split = c(1:4),
        height = unit(4,"cm"),
        width=unit(3,"cm"),
        column_names_side = "top",
        column_names_centered = T,
        column_names_rot = 0,
        column_names_gp= gpar(fontsize=8,angle=0),
        show_heatmap_legend = FALSE,
        left_annotation = rowAnnotation(label = anno_block(width=unit(0.5,"cm"),gp = gpar(fill = ColorsTreatment),
labels = c("Naive", "Sham", "1d","3d"), labels_gp = gpar(fontsize=8,col = c("black","white","white","white")))), row_title = NULL)

HMLeg2<-grid.grabExpr(draw(Legend(col_fun = col_fun, 
                                  direction = "horizontal",
                                 legend_width = unit(2.5,"cm"),
                                  grid_height = unit(1,"mm"),
                                  at=c(-2,0,2),
                                 title = "Phase Score (a.u.)",
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  title_gp = gpar(col = "black",angle=90,
                                                  fontface="plain",
                                                  fontsize=8))))
HMPhase<-plot_grid(grid.grabExpr(draw(HM)),HMLeg,rel_heights = c(4,1),nrow=2)
```


# EDU
```{r}
tab<-read.csv("/Users/alinakline-schoder/Documents/SavedData/2022_07_EDU.csv")

tab$MGCount<-tab$MG/tab$Total.Cells
tab$ProlifMG<-tab$Prolif.MG/tab$MG
tab$Prolif<-tab$Prolif.Cells/tab$Total.Cells

tab<-pivot_longer(tab,cols = c("MGCount","ProlifMG","Prolif"))

ColorsGroup_NoSham<-c("#FFFFFF","#75A0B2","#205F83","gray","gray")
my_comparisons <- list( c("Naive", "1d"), c("Naive", "3d"), c("1d", "3d") )
tab$Group<-factor(tab$Group,levels=c("Naive","1d","3d"))
sub<-tab[tab$name=="MGCount",]
EDU1<-ggplot(sub,aes(x=Group,y=value))+geom_boxplot(color="black",aes(fill=Group))+geom_point (color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+ ylab("Microglia (%)") +
  stat_compare_means(comparisons = my_comparisons,method = "t.test",size=3)+ylim(0,12.5)+ThemeBoxPlot

sub<-tab[tab$name=="Prolif",]
EDU3<-ggplot(sub,aes(x=Group,y=value))+geom_boxplot(color="black",aes(fill=Group))+geom_point (color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+ylab("Proliferating Cells (%)") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=3)+ylim(0,0.85)+ThemeBoxPlot

sub<-tab[tab$name=="ProlifMG",]
EDU2<-ggplot(sub,aes(x=Group,y=value*100))+geom_boxplot(color="black",aes(fill=Group))+geom_point (color="black")+scale_fill_manual(values=ColorsGroup_NoSham)+ylab("Proliferating Microglia (%)") + stat_compare_means(comparisons = my_comparisons,method = "t.test",size=3)+ylim(0,2)+ThemeBoxPlot

```

# Putting it together and saving
```{r}
Fig2a<-Dim+theme(legend.position = "none")
Fig2b<-Feat
Fig2c<-Dis
Fig2d<-HM_ReadyGenes
Fig2e<-OntoPlot
Fig2f<-HMPhase
Fig2h<-ggplot() + theme_void()

Fig2i<-plot_grid(EDU1,EDU2,EDU3,nrow=1)

HMPhase<-plot_grid(grid.grabExpr(draw(HMPhase1+HMPhase2)),plot_grid(HMLeg2,HMLeg1),rel_heights = c(4,1),nrow=2)

Top<-plot_grid(Fig2a,FeatLeg,Feat,Fig2c,nrow=1,labels = c("a","b","","c"),align="h",axis="b",rel_widths = c(1,0.1,1.5,1))
Middle<-plot_grid(Fig2d,Fig2e,nrow=1,labels = c("d","e"))
Next<-plot_grid(HMPhase,Fig2h,nrow=1,labels=c("f","g"))

Full<-plot_grid(Top,Middle,Next,Fig2i,nrow=4,labels=c("","","","h"))
ggsave("Figure2-MGDEG.png",width = 8,height = 10,units = "in",bg="white")

```


