---
title: "Figure 2"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---
# Figure 3 - Microglia Clustering and DAM

```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
library(BiocManager)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
library(sjmisc)
library(ggrepel)
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "orange"))

load("/Users/alinakline-schoder/Documents/SavedData/7-CAMFigure.RData")
load("/Users/alinakline-schoder/Documents/SavedData/3-AllCells.RData")
Integrated$Treatment<-factor(Integrated$Treatment,levels=c("Naive","Sham","1d BBBO","3d BBBO"))
CAM$clusters_labeled<-recode(CAM$seurat_clusters,
                     "1"="H2-Ab1+",
                     "2"="Mrc1+",
                     "0"="Ccl2+")
ColorsTreatment<-c("#FFFFFF","#A3A3A3","#75A0B2","#205F83")
names(ColorsTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
LinesTreatment<-c("#A3A3A3",ColorsTreatment[2:4])
names(LinesTreatment)<-c("Naive","Sham","1d BBBO","3d BBBO")
ColorMacrophageClusters<-c("#F3B3A6","#3d405b","#81b29a")
names(ColorMacrophageClusters)<-levels(CAM$clusters_labeled)
Colors_Feat<-colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "orange"))
CAM$Phase<-factor(CAM$Phase,levels = c("G0","G1S","S","G2M","M","MG1"))
```
# Setting themes
```{r}
ThemeAll<-theme(legend.position = "none",
                panel.grid = element_blank(),
                axis.text = element_text(size=8),
                axis.title = element_text(size=10),
                plot.margin = margin(0.5,0.5,0.25,0.25,"cm"),
                strip.text=element_text(size=10),
                axis.line = element_line(size=0.5,color="black"),
                plot.title = element_blank(),
                panel.background = element_blank())

ThemeLeg<-theme(legend.position = "right",
        legend.direction = "vertical",
        legend.box = "vertical",
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        legend.box.spacing = margin(-0.5,0.5,0.25,0,"cm"),
        legend.text = element_text(size=8),
        legend.title = element_text(size=8))

ThemeOnto<-ThemeAll+ThemeLeg+theme(axis.title = element_blank(),axis.line = element_blank(),axis.ticks = element_blank())
        
ThemeUMAP<-ThemeAll+theme(axis.ticks = element_blank(),
                 axis.text = element_blank())
ThemeVolcano<-ThemeAll

ThemeBoxPlot<-ThemeAll+theme(axis.title.x = element_blank())
```

# Featureplot
```{r}
DefaultAssay(CAM)<-"RNA"
Feat<-FeaturePlot(CAM,features = c("Mrc1","H2-Ab1","Ccl2","Cd74","Cd163","Thbs1"),ncol=3,cols = c("#D3D3D3","orange"))&ThemeUMAP&theme(axis.title = element_blank())


FeatLeg<-grid.grabExpr(draw(Legend(col_fun = colorRamp2(c(0, 100), c("#D3D3D3","orange")), 
                                  direction = "horizontal",
                                 legend_width = unit(2.5,"cm"),
                                  grid_height = unit(1,"mm"),
                                  at=c(0,50,100),
                                 labels=c("","",""),
                                 title = "Normalized Expression",
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=6),
                                  title_gp = gpar(col = "black",angle=90,
                                                    
                                                  fontface="plain",
                                                  fontsize=8))))

```


# Clusters UMAP
```{r}
Dim1<-DimPlot(CAM,group.by = "clusters_labeled",label=FALSE,cols = ColorMacrophageClusters,pt.size = 0.5)+ThemeUMAP+scale_y_continuous(limits=c(-6.5,5))+scale_x_continuous(limits=c(-5,7))
```


# Heatmap
```{r}
Idents(CAM)<-"Treatment"
Genes2Plot<-CAM_Treatment_Markers%>%
    group_by(cluster) %>%
    top_n(n = 15, wt = avg_log2FC)
Sub<-subset(CAM,downsample=200)
Data<-t(as.matrix(Sub@assays$SCT@data[unique(Genes2Plot$gene),]))
Data<-cbind(as.data.frame(Data),Sub$clusters_labeled,Sub$Treatment)
colnames(Data)[dim(Data)[2]-1]<-"Cluster"
colnames(Data)[dim(Data)[2]]<-"Treatment"
Data<-Data[order(Data$Treatment,Data$Cluster),]
Treatment<-Data$Treatment
Cluster<-Data$Cluster
Data<-Data[,1:(dim(Data)[2]-2)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(ColorsTreatment)<-levels(CAM$Treatment)

HM<-Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            column_title = NULL,
            show_column_names = FALSE,
            row_names_side = "left",
            top_annotation = HeatmapAnnotation(label = anno_block(gp = gpar(fill = ColorsTreatment),
labels = c("", "Sham", "1d","3d"), labels_gp = gpar(fontsize=8,col = c("black","white","white","white"))),Cluster=anno_simple(as.character(Cluster),height=unit(2,"mm"),col = ColorMacrophageClusters,border = TRUE),show_annotation_name = F),

            col=col_fun,
            show_heatmap_legend = FALSE,
            row_names_gp = gpar(fontsize=8),
            column_split = Treatment,
column_labels = NULL)



HMLegGene<-grid.grabExpr(draw(Legend(col_fun = col_fun, 
                                  direction = "horizontal",
                                 legend_width = unit(2.5,"cm"),
                                  grid_height = unit(1,"mm"),
                                  at=c(-2,0,2),
                                 title = "Normalized Expression",
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  title_gp = gpar(col = "black",angle=90,
                                                  fontface="plain",
                                                  fontsize=8))))
HMGenes<-grid.grabExpr(draw(HM))
```

# Volcano plots
```{r}
toptable <- as.data.frame(Markers_1d)
toptable$lab <- rownames(Markers_1d)
Genes<-c("Ccl2","Ccl4","Fos","Il1b","Pf4","Ccl12","Malat1")
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA
toptable[abs(toptable$avg_log2FC)<1,]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "FC")
ylab<-bquote(~-Log[10] ~ italic(P))
toptable$Significant<-"black"
toptable[toptable$p_val_adj<0.05,]$Significant<-ColorsTreatment[3]

Volcano24<-ggplot(toptable, aes(x = xvals, y = yvals)) + geom_point(na.rm = TRUE,size=0.1,color=toptable$Significant)+xlab(xlab) + ylab(ylab) + geom_label_repel(aes(label=lab),size=3,label.padding = unit(0.1, "lines"))+scale_y_continuous(expand=c(0,0))+ThemeVolcano





toptable <- as.data.frame(Markers_3d)
toptable$lab <- rownames(Markers_3d)
Genes<-c("Malat1","Ifitm3","Fos","Mrc1","Vim")
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA
toptable[abs(toptable$avg_log2FC)<1,]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "FC")
ylab<-bquote(~-Log[10] ~ italic(P))
toptable$Significant<-"black"
toptable[toptable$p_val_adj<0.05,]$Significant<-ColorsTreatment[4]


Volcano72<-ggplot(toptable, aes(x = xvals, y = yvals)) + geom_point(na.rm = TRUE,size=0.1,color=toptable$Significant)+xlab(xlab) + ylab(ylab) + geom_label_repel(aes(label=lab),size=3,label.padding = unit(0.1, "lines"))+ThemeVolcano+scale_y_continuous(expand=c(0,0))
```

# bar charts
```{r}
tab<-as.data.frame(table(CAM$Treatment,CAM$Phase))
tot<-as.data.frame(table(CAM$Treatment))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
tab<-tab[,setdiff(colnames(tab),"Freq")]
tab<-as.data.frame(pivot_wider(tab,names_from = Var2,values_from = Freq_Norm))
rownames(tab)<-tab$Var1
tab<-tab[,setdiff(colnames(tab),"Var1")]

HMPhase2<-Heatmap(as.matrix(tab),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        show_row_names = FALSE,
        show_column_names = TRUE,
        row_names_side = "left",
        col = colorRamp2(c(0, 100), c("white", "black")),
        row_split = c(1:4),
        height = unit(4,"cm"),
        width=unit(5,"cm"),
        column_names_side = "top",
        column_names_centered = T,
        column_names_rot = 0,
        column_names_gp= gpar(fontsize=8,angle=0),
        show_heatmap_legend = FALSE,
        left_annotation = rowAnnotation(label = anno_block(width=unit(0.5,"cm"),gp = gpar(fill = ColorsTreatment),
labels = c("Naive", "Sham", "1d","3d"), labels_gp = gpar(fontsize=8,col = c("black","white","white","white")))), row_title = NULL)

HMLeg1<-grid.grabExpr(draw(Legend(col_fun = colorRamp2(c(0, 100), c("white", "black")), 
                                  direction = "horizontal",
                                 legend_width = unit(2.5,"cm"),
                                  grid_height = unit(1,"mm"),
                                  at=c(0,50,100),
                                 title = "Assigned Phase (%)",
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  title_gp = gpar(col = "black",angle=90,
                                                    
                                                  fontface="plain",
                                                  fontsize=8))))

Idents(CAM)<-"Treatment"
dot_data<-data.frame(Treatment=CAM$Treatment,G1S=CAM$G1S.Score,S=CAM$S.Score,G2M=CAM$G2M.Score,M=CAM$M.Score,MG1=CAM$MG1.Score)

dot_data <- dot_data %>%
  group_by(Treatment) %>%
  summarize(G1S=mean(G1S),S=mean(S),G2M=mean(G2M),M=mean(M),MG1=mean(MG1))
dot_data<-as.data.frame(dot_data)
rownames(dot_data)<-dot_data$Treatment
dot_data<-dot_data[,setdiff(colnames(dot_data),"Treatment")]



HMPhase1<-Heatmap(as.matrix(dot_data),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        show_row_names = FALSE,
        show_column_names = TRUE,
        row_names_side = "left",
        col = col_fun,
        row_split = c(1:4),
        height = unit(4,"cm"),
        width=unit(5,"cm"),
        column_names_side = "top",
        column_names_centered = T,
        column_names_rot = 0,
        column_names_gp= gpar(fontsize=8,angle=0),
        show_heatmap_legend = FALSE,
        left_annotation = rowAnnotation(label = anno_block(width=unit(0.5,"cm"),gp = gpar(fill = ColorsTreatment),
labels = c("Naive", "Sham", "1d","3d"), labels_gp = gpar(fontsize=8,col = c("black","white","white","white")))), row_title = NULL)

HMLeg2<-grid.grabExpr(draw(Legend(col_fun = col_fun, 
                                  direction = "horizontal",
                                 legend_width = unit(2.5,"cm"),
                                  grid_height = unit(1,"mm"),
                                  at=c(-2,0,2),
                                 title = "Phase Score (a.u.)",
                                  labels_gp = gpar(col = "black",
                                                  fontface="plain",
                                                  fontsize=8),
                                  title_gp = gpar(col = "black",angle=90,
                                                  fontface="plain",
                                                  fontsize=8))))
```


# ontology
```{r}
KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(italic(P[Fis]))

Terms<-c("cytokine activity",
         "response to chemokine",
         "extracellular exosome",
         "macrophage migration",
         "defense response",
         "innate immune response",
         "inflammatory response",
         "endosome",
         "macrophage activation",
         "cell migration")
Onto_1d$Treatment<-"1d"
Onto_3d$Treatment<-"3d"
All<-rbind(Onto_1d,Onto_3d)
OntoPlotdata<-All[All$Term %in% Terms,]
library(scales) 

OntoPlot<-ggplot(OntoPlotdata,aes(x=Treatment,y=Term,color=-log(PVal_KS),size=PCT))+
  geom_point()+ThemeOnto+viridis::scale_color_viridis(guide=guide_colorbar(title=KSLab,title.position = "top"))+ scale_size_continuous(guide=guide_legend(title="Genes (%)",title.position = "top"),breaks = c(10,35,60),limits=c(10,60),range = c(0.5,4))

```



# Pie chart
```{r}
tab<-as.data.frame(table(Integrated$Treatment,Integrated$cell_type))
tot<-as.data.frame(table(Integrated$Treatment))
rownames(tot)<-tot$Var1
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq
tab<-tab[tab$Var2=="CAM",]
tab$Var1<-recode(tab$Var1,"1d BBBO"="1d","3d BBBO"="3d")
names(ColorsTreatment)<-levels(tab$Var1)
names(LinesTreatment)<-levels(tab$Var1)
Pie<-ggplot(tab,aes(x=Var1,y=Freq_Norm*100,fill=Var1,color=Var1))+stat_summary(fun="mean",geom="bar")+scale_fill_manual(values=ColorsTreatment)+scale_color_manual(values=LinesTreatment)+scale_y_continuous(limits = c(0,0.65),breaks = c(0,0.25,0.5),labels=c("0%","25%","50%"),expand = c(0,0),position = "right") + scale_y_continuous(expand = c(0,0)) + 
  ylab("CAM (% of All Cells)") + 
  xlab("Treatment")+ThemeBoxPlot
```

```{r}
library(scales)
tab<-as.data.frame(table(Integrated$orig.ident,Integrated$Treatment,Integrated$cell_type))
tab<-tab[tab$Var3=="CAM"|tab$Var3=="Microglia",]

Tota<-as.data.frame(table(Integrated$orig.ident,Integrated$Treatment))
Tota$Full<-paste(Tota$Var1,Tota$Var2)
tab$Full<-paste(tab$Var1,tab$Var2)
rownames(Tota)<-Tota$Full
tab$Total<-Tota[tab$Full,]$Freq
tab<-tab[tab$Total>0,]
tab$Freq_Adj<-tab$Freq/tab$Total
Percent<-ggplot(tab,aes(x=Var2,y=Freq_Adj*100,fill=Var2,color=Var2))+stat_summary(fun="mean",geom="bar")+scale_fill_manual(values=ColorsTreatment)+scale_color_manual(values=LinesTreatment)+stat_compare_means(method="anova",label.y = 40,size=3) + scale_y_continuous(expand = c(0,0),labels = scales::percent)+ylab("CAM (% of All Cells)")+ThemeBoxPlot

```



# treatment split by cluster
```{r}
tab<-as.data.frame(table(CAM$Treatment,CAM$clusters_labeled))
tot<-as.data.frame(table(CAM$Treatment))
tab$Freq_Norm<-tab$Freq/tot[tab$Var1,]$Freq*100
tab<-tab[,setdiff(colnames(tab),"Freq")]
tab$Var1<-recode(tab$Var1,"1d BBBO"="1d","3d BBBO"="3d")
Dis<-ggplot(tab,aes(x=Var1,y=Freq_Norm,fill=Var2))+geom_bar(position="fill", stat="identity")+scale_fill_manual(values=ColorMacrophageClusters)+ylab("Cluster Size")+ThemeBoxPlot+scale_y_continuous(expand=c(0,0))
```


# Putting it all together
```{r}

BottomLegs<-plot_grid(HMLeg2,HMLeg1,HMLegGene,nrow=1,rel_widths = c(1,1,1))


DisLeg<-get_legend(Dis+theme(legend.position="top",legend.key.size = unit(0.1,"cm"),legend.title = element_blank()))

TopLeg<-plot_grid(DisLeg,FeatLeg,DisLeg,nrow=1,rel_widths = c(1,1.5,1),labels=c("a","b","c"))
TopPlots<-plot_grid(Dim1+theme(plot.margin = margin(0,0.5,0.25,0.25,"cm")),Feat&theme(plot.margin = margin(0,0.5,0.25,0.25,"cm"),plot.title=element_text(size=10)),Dis+theme(plot.margin = margin(0,0.5,0.25,0.25,"cm")),nrow=1,rel_widths = c(1,1.5,1),align="h",axis="b")
Mid<-plot_grid(OntoPlot,Pie,nrow=1,rel_widths = c(1.5,1),labels=c("g","h"))

Left<-plot_grid(plot_grid(Volcano24,Volcano72,nrow=1,labels = c("d","e")),Mid,grid.grabExpr(draw(HMPhase1+HMPhase2)),nrow=3,labels=c("","","i"))

Full<-plot_grid(TopLeg,TopPlots,plot_grid(Left,HMGenes,nrow=1,rel_widths = c(2,1),labels=c("","f")),BottomLegs,nrow=4,rel_heights = c(0.15,0.75,2,0.15))

ggsave("Figure4-CAM.png",width = 8,height = 10,units = "in",bg="white")
```

