---
title: "Figure 2"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---


```{r message=FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(reshape2)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(gridExtra)
library(here)
library(RColorBrewer)
library(ComplexHeatmap)
library(ggrepel)
ColorsTreatment_Full<-c(brewer.pal(6,"Set1"),brewer.pal(3,"Pastel2"))
ColorsTreatment<-c("#BD6B73","#CCAD8F","#CCAD8F","#CCAD8F","#CCAD8F","#81C3D7","#16425B")
Colorssub<-unname(ColorsTreatment[c("24h FUS+MB","72h FUS+MB")])
Colors_FUS_Group_Broad<-c(ColorsTreatment[1],ColorsTreatment[2],Colorssub)
ColorPhase<-rev(c("gray",brewer.pal(5,"Pastel2")))

ColorMacrophageClusters<-brewer.pal(3,"Set2")

library(circlize)
Colors_GeneExp = colorRamp2(c(-2, 0, 2), c("green", "white", "red"))
Colors_Feat<-c("red","green")

th <- theme_bw() + theme(legend.background = element_rect(),
                         plot.title = element_text(angle = 0, size = 10, vjust = 1), 
                                         plot.caption = element_blank(), 
                                         axis.text = element_text(angle = 0,
                                                                  size = 6,
                                                                  vjust = 1), 
                                         legend.position = "none",
                         axis.title = element_text(size=8),
                         panel.grid.major = element_blank())

FCcutoff<-0.5
pCutoff<-0.05
```
# Loading
```{r}
setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync")
load("5-IntegratedMicroglia.RData")
load("5-CellCycle.RData")
```


# Prepping
```{r}
Microglia$Treatment_New<-recode(Microglia$Treatment_Specific,
                                 "FUSMB_450_24h_Ipsi"="24h FUS+MB",
                                 "FUSMB_450_72h_Ipsi"="72h FUS+MB",
                                "MB_24h" = "24h MB",
                                "MB_72h" = "72h MB",
                                "FUS_450kPa_24h"="24h FUS",
                                "FUS_450kPa_72h"="72h FUS")

Microglia$Treatment_New<-factor(Microglia$Treatment_New,levels=c("Naive","24h MB","72h MB","24h FUS","72h FUS","24h FUS+MB","72h FUS+MB"))
Shams<-c("Naive","24h MB","72h MB","24h FUS","72h FUS")
Macrophages$Treatment_New<-recode(Macrophages$Treatment_Specific,
                                 "FUSMB_450_24h_Ipsi"="24h FUS+MB",
                                 "FUSMB_450_72h_Ipsi"="72h FUS+MB",
                                "MB_24h" = "24h MB",
                                "MB_72h" = "72h MB",
                                "FUS_450kPa_24h"="24h FUS",
                                "FUS_450kPa_72h"="72h FUS")
Macrophages$Treatment_New<-factor(Macrophages$Treatment_New,levels=c("Naive","24h MB","72h MB","24h FUS","72h FUS","24h FUS+MB","72h FUS+MB"))

Macrophages$hicat_clusters<-ordered(Macrophages$hicat_clusters,levels=c("4","1","5"))
Macrophages$clusters_labeled<-recode(Macrophages$hicat_clusters,
                                 "4"="H2-Ab1+",
                                 "1"="Mrc1+",
                                 "5"="F10+")
Macrophages$Phase<-factor(Macrophages$Phase,levels = c("G0","G1S","S","G2M","M","MG1"))
names(ColorsTreatment)<-levels(Microglia$Treatment_New)
```

# Microglia Markers
```{r}
setwd('/Users/alinakline-schoder/Documents/Papers/MicrogliaPaper-Joint/FUSMicroglia/2021-JointPaper/ImportantFiles')
Barres<-read.csv(file = 'BarresCellStateGenes.csv')
source('AKS_CellCycleScoring.R')
AllGenes<-rownames(Microglia@assays$RNA)
G2M<-as.character(Barres[Barres$G2.M %in% AllGenes,]$G2.M)
MG1<-as.character(Barres[Barres$M.G1 %in% AllGenes,]$M.G1)
G1S<-as.character(Barres[Barres$G1.S %in% AllGenes,]$G1.S)
S<-as.character(Barres[Barres$S %in% AllGenes,]$S)
M<-as.character(Barres[Barres$M %in% AllGenes,]$M)

Matrix<-Microglia@assays$RNA@counts
Matrix_Sub<-as.data.frame(t(Matrix[S,]))
Matrix_Sub$Cell_Sum<-rowSums(Matrix_Sub)
Cor<-cor(as.matrix(Matrix_Sub))
Cor<-Cor[dim(Cor)[2],]
Cor<-Cor[names(Cor)!="Cell_Sum"]
Cor[is.na(Cor)]<-0
S.Genes <- names(Cor[Cor>0.3])

Matrix_Sub<-as.data.frame(t(Matrix[G2M,]))
Matrix_Sub$Cell_Sum<-rowSums(Matrix_Sub)
Cor<-cor(as.matrix(Matrix_Sub))
Cor<-Cor[dim(Cor)[2],]
Cor<-Cor[names(Cor)!="Cell_Sum"]
Cor[is.na(Cor)]<-0
G2M.Genes <- names(Cor[Cor>0.3])

Matrix_Sub<-as.data.frame(t(Matrix[MG1,]))
Matrix_Sub$Cell_Sum<-rowSums(Matrix_Sub)
Cor<-cor(as.matrix(Matrix_Sub))
Cor<-Cor[dim(Cor)[2],]
Cor<-Cor[names(Cor)!="Cell_Sum"]
Cor[is.na(Cor)]<-0
MG1.Genes <- names(Cor[Cor>0.3])

Matrix_Sub<-as.data.frame(t(Matrix[G1S,]))
Matrix_Sub$Cell_Sum<-rowSums(Matrix_Sub)
Cor<-cor(as.matrix(Matrix_Sub))
Cor<-Cor[dim(Cor)[2],]
Cor<-Cor[names(Cor)!="Cell_Sum"]
Cor[is.na(Cor)]<-0
G1S.Genes <- names(Cor[Cor>0.3])

Matrix_Sub<-as.data.frame(t(Matrix[M,]))
Matrix_Sub$Cell_Sum<-rowSums(Matrix_Sub)
Cor<-cor(as.matrix(Matrix_Sub))
Cor<-Cor[dim(Cor)[2],]
Cor<-Cor[names(Cor)!="Cell_Sum"]
Cor[is.na(Cor)]<-0
M.Genes <- names(Cor[Cor>0.3])

DefaultAssay(Microglia)<-"RNA"
Microglia<-NormalizeData(Microglia)
Microglia<-AKS_CellCycle(Microglia,s.features = S.Genes,g1s.features=G1S.Genes,g2m.features = G2M.Genes,m.features = M.Genes,mg1.features = MG1.Genes)
Data_New<-as.data.frame(cbind(Microglia$G1S.Score,Microglia$S.Score,Microglia$G2M.Score,Microglia$M.Score,Microglia$MG1.Score))
Data_New<-as.data.frame(as.matrix(scale(Data_New,scale = TRUE,center=TRUE)))
colnames(Data_New)<-c("G1S","S","G2M","M","MG1")

Microglia$G1S.Score<-Data_New$G1S
Microglia$S.Score<-Data_New$S
Microglia$G2M.Score<-Data_New$G2M
Microglia$M.Score<-Data_New$M
Microglia$MG1.Score<-Data_New$MG1

Scores<-Data_New
Scores$MaxScore<-apply(Scores,1,max)
Scores$Assignment1<-colnames(Scores)[apply(Scores,1,which.max)]
Scores[Scores$MaxScore<1,]$Assignment1<-"G0"
Microglia$Phase<-factor(Scores$Assignment1,levels = c("G0","G1S","S","G2M","M","MG1"))

#Plotting
Scores$Assignment2<-Scores$Assignment1
Scores$Assignment3<-Scores$Assignment1
Scores[Scores$Assignment1=="G1S",]$Assignment2<-"G1S.S"
Scores[Scores$Assignment1=="G1S",]$Assignment3<-"MG1.G1S"
Scores[Scores$Assignment1=="S",]$Assignment2<-"G1S.S"
Scores[Scores$Assignment1=="S",]$Assignment3<-"S.G2M"
Scores[Scores$Assignment1=="G2M",]$Assignment2<-"G2M.M"
Scores[Scores$Assignment1=="G2M",]$Assignment3<-"S.G2M"
Scores[Scores$Assignment1=="M",]$Assignment2<-"G2M.M"
Scores[Scores$Assignment1=="M",]$Assignment3<-"M.MG1"
Scores[Scores$Assignment1=="MG1",]$Assignment2<-"MG1.G1S"
Scores[Scores$Assignment1=="MG1",]$Assignment3<-"M.MG1"

G1S<-cor(t(Data_New),     c( 2,-2,-2,-2,-2))
G1S.S<-cor(t(Data_New),   c( 2, 2,-2,-2,-2))
S<-cor(t(Data_New),       c(-2, 2,-2,-2,-2))
S.G2M<-cor(t(Data_New),   c(-2, 2,2,-2,-2))
G2M<-cor(t(Data_New),     c(-2,-2,2,-2,-2))
G2M.M<-cor(t(Data_New),   c(-2,-2,2,2,-2))
M<-cor(t(Data_New),       c(-2,-2,-2,2,-2))
M.MG1<-cor(t(Data_New),   c(-2,-2,-2,2,2))
MG1<-cor(t(Data_New),     c(-2,-2,-2,-2,2))
MG1.G1S<-cor(t(Data_New), c( 2,-2,-2,-2,2))
G0<-cor(t(Data_New),      c(-2,-2,-2,-2,-1.999999))
  
Correlations<-cbind(G1S,G1S.S,S,S.G2M,G2M,G2M.M,M,M.MG1,MG1,MG1.G1S,G0)
colnames(Correlations)<-c("G1S","G1S.S","S","S.G2M","G2M","G2M.M","M","M.MG1","MG1","MG1.G1S","G0")
FindingMax<-data.frame(Correlation1=Correlations[cbind(1:dim(Scores)[1],match(Scores$Assignment1,colnames(Correlations)))])
FindingMax$Correlation2<-as.numeric(Correlations[cbind(1:dim(Scores)[1],match(Scores$Assignment2,colnames(Correlations)))])
FindingMax$Correlation3<-Correlations[cbind(1:dim(Scores)[1],match(Scores$Assignment3,colnames(Correlations)))]
FindingMax$Correlation_G0<-Correlations[cbind(1:dim(Scores)[1],dim(Correlations)[2])]
Which<-apply(FindingMax,1,which.max)
Max<-apply(FindingMax,1,max)
Which[Max<0.75]<-"4"
Options<-cbind(Scores$Assignment1,Scores$Assignment2,Scores$Assignment3,"G0")
Assignnment<-data.frame(Chosen=Options[cbind(1:dim(Scores)[1],as.numeric(Which))],Max=Max)
Assignnment$Chosen<-as.character(Assignnment$Chosen)
Assignnment$Max<-as.numeric(as.character(Assignnment$Max))
#Ordering data for heatmap
  
Assignnment$Chosen<-factor(Assignnment$Chosen,levels=c("MG1.G1S","G1S","G1S.S","S","S.G2M","G2M","G2M.M","M","M.MG1","MG1","G0"))
Data_New<-Data_New[order(Assignnment$Chosen,-Assignnment$Max),]
AssignnmentNew<-Assignnment[order(Assignnment$Chosen,-Assignnment$Max),]

```

# Microglia
```{r}
Idents(Microglia)<-"Treatment_New"
DefaultAssay(Microglia)<-"RNA"
Microglia<-ScaleData(Microglia)
Markers_MB24<-FindMarkers(Microglia,ident.1 = "24h MB",ident.2="Naive",slot="scale.data")
Markers_MB72<-FindMarkers(Microglia,ident.1 = "72h MB",ident.2="Naive",slot="scale.data")
Markers_FUS24<-FindMarkers(Microglia,ident.1 = "24h FUS",ident.2="Naive",slot="scale.data")
Markers_FUS72<-FindMarkers(Microglia,ident.1 = "72h FUS",ident.2="Naive",slot="scale.data")



toptable <- as.data.frame(Markers_MB24)
toptable$lab <- rownames(Markers_MB24)
toptable$n<-nchar(toptable$lab)
toptable[toptable$n>5,]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA

toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
toptable[toptable$yvals>300,]$yvals<-300
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))

MG_Volcano_MB24 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1)+ labs(title = 'MB 24h')+xlab(xlab) + ylab(ylab) + geom_text_repel(aes(label=lab),size=2,max.overlaps = 20,segment.size=0.1)+scale_y_continuous(limits=c(0,300),breaks=c(0,150,300),labels = c(0,150,"300+"))+scale_x_continuous(limits=c(-2,2))


toptable <- as.data.frame(Markers_MB72)
toptable$lab <- rownames(Markers_MB72)
toptable$n<-nchar(toptable$lab)
toptable[toptable$n>5,]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA

toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))

MG_Volcano_MB72 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1)+ labs(title = 'MB 72h')+xlab(xlab) + ylab(ylab) + geom_text_repel(aes(label=lab),size=2,max.overlaps = 20,segment.size=0.1)+scale_y_continuous(limits=c(0,300),breaks=c(0,150,300),labels = c(0,150,"300+"))+scale_x_continuous(limits=c(-2,2))


toptable <- as.data.frame(Markers_FUS24)
toptable$lab <- rownames(Markers_FUS24)
toptable$n<-nchar(toptable$lab)
toptable[toptable$n>5,]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA

toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))

MG_Volcano_FUS24 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1)+ labs(title = 'FUS 24h')+xlab(xlab) + ylab(ylab) + geom_text_repel(aes(label=lab),size=2,max.overlaps = 20,segment.size=0.1)+scale_y_continuous(limits=c(0,300),breaks=c(0,150,300),labels = c(0,150,"300+"))+scale_x_continuous(limits=c(-2,2))

toptable <- as.data.frame(Markers_FUS72)
toptable$lab <- rownames(Markers_FUS72)
toptable$n<-nchar(toptable$lab)
toptable[toptable$n>5,]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA

toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))

MG_Volcano_FUS72 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1)+ labs(title = 'FUS 72h')+xlab(xlab) + ylab(ylab) + geom_text_repel(aes(label=lab),size=2,max.overlaps = 20,segment.size=0.1)+scale_y_continuous(limits=c(0,300),breaks=c(0,150,300),labels = c(0,150,"300+"))+scale_x_continuous(limits=c(-2,2))
```

# Macrophage
```{r}
Idents(Macrophages)<-"Treatment_New"
DefaultAssay(Macrophages)<-"RNA"
Macrophages<-ScaleData(Macrophages)
Markers_MB24<-FindMarkers(Macrophages,ident.1 = "24h MB",ident.2="Naive",slot="scale.data")
Markers_MB72<-FindMarkers(Macrophages,ident.1 = "72h MB",ident.2="Naive",slot="scale.data")
Markers_FUS24<-FindMarkers(Macrophages,ident.1 = "24h FUS",ident.2="Naive",slot="scale.data")
Markers_FUS72<-FindMarkers(Macrophages,ident.1 = "72h FUS",ident.2="Naive",slot="scale.data")

Markers_MB24$pct.dif<-Markers_MB24$pct.1-Markers_MB24$pct.2
Markers_MB72$pct.dif<-Markers_MB72$pct.1-Markers_MB72$pct.2
Markers_FUS24$pct.dif<-Markers_FUS24$pct.1-Markers_FUS24$pct.2
Markers_FUS72$pct.dif<-Markers_FUS72$pct.1-Markers_FUS72$pct.2

toptable <- as.data.frame(Markers_MB24)
toptable$lab <- rownames(Markers_MB24)
toptable$n<-nchar(toptable$lab)
toptable[toptable$n>5,]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA

toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))

CAM_Volcano_MB24 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1)+ labs(title = 'MB 24h')+xlab(xlab) + ylab(ylab) + geom_text_repel(aes(label=lab),size=2,max.overlaps = 20,segment.size=0.1)+scale_y_continuous(limits=c(0,50))+scale_x_continuous(limits=c(-2,2))

toptable <- as.data.frame(Markers_MB72)
toptable$lab <- rownames(Markers_MB72)
toptable$n<-nchar(toptable$lab)
toptable[toptable$n>5,]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA

toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))

CAM_Volcano_MB72 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1)+ labs(title = 'MB 72h')+xlab(xlab) + ylab(ylab) + geom_text_repel(aes(label=lab),size=2,max.overlaps = 20,segment.size=0.1)+scale_y_continuous(limits=c(0,50))+scale_x_continuous(limits=c(-2,2))

toptable <- as.data.frame(Markers_FUS24)
toptable$lab <- rownames(Markers_FUS24)
toptable$n<-nchar(toptable$lab)
toptable[toptable$n>5,]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA

toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))

CAM_Volcano_FUS24 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1)+ labs(title = 'FUS 24h')+xlab(xlab) + ylab(ylab) + geom_text_repel(aes(label=lab),size=2,max.overlaps = 20,segment.size=0.1)+scale_y_continuous(limits=c(0,50))+scale_x_continuous(limits=c(-2,2))

toptable <- as.data.frame(Markers_FUS72)
toptable$lab <- rownames(Markers_FUS72)
toptable$n<-nchar(toptable$lab)
toptable[toptable$n>5,]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA

toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))

CAM_Volcano_FUS72 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1)+ labs(title = 'FUS 72h')+xlab(xlab) + ylab(ylab) + geom_text_repel(aes(label=lab),size=2,max.overlaps = 20,segment.size=0.1)+scale_y_continuous(limits=c(0,50))+scale_x_continuous(limits=c(-2,2))
```



# Barcharts
```{r}
dat<-as.data.frame(table(Microglia$Treatment_New,Microglia$Phase))
dat$Treatment<-dat$Var1
dat$Phase<-dat$Var2
levels(dat$Treatment)<-levels(dat$Treatment)
Microglia_BC<-ggplot(dat) + 
  geom_bar(position="fill",stat="identity",aes(y=Treatment,x=Freq,fill=Phase)) + scale_fill_manual(values = rev(ColorPhase),guide=guide_legend(nrow = 2)) + 
  geom_tile(aes(x=-0.03,y=Treatment),fill=ColorsTreatment[dat$Var1],width=0.05) + scale_x_continuous(breaks = c(0,0.5,1),labels=c("0%","50%","100%")) + theme_minimal() +
  theme(legend.position="top",
        axis.title = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.25,"line"),
        plot.margin = margin(0,0.5,0.5,0.5,"cm"))

ColorMacrophageClusters<-brewer.pal(3,"Set1")

dat<-as.data.frame(table(Macrophages$Treatment_New,Macrophages$clusters_labeled))
dat$Treatment<-dat$Var1
dat$Cluster<-dat$Var2
levels(dat$Treatment)<-levels(dat$Treatment)
Macrophage_BC<-ggplot(dat) + 
  geom_bar(position="stack",stat="identity",aes(y=Treatment,x=Freq,fill=Cluster)) + scale_fill_manual(values = ColorMacrophageClusters,guide=guide_legend(nrow = 2)) + 
  geom_tile(aes(x=-20,y=Treatment),fill=ColorsTreatment[dat$Var1],width=35) + theme_minimal() +
  theme(legend.position="top",
        axis.title = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.25,"line"),
        plot.margin = margin(0,0.5,0.5,0.5,"cm"))+xlab("Count")
```


#All Plots
```{r}
A<-plot_grid(MG_Volcano_MB24,CAM_Volcano_MB24,nrow=2,align = "v",axis = "lr",labels = c("A","F"))
B<-plot_grid(MG_Volcano_MB72,CAM_Volcano_MB72,nrow=2,align = "v",axis = "lr",labels = c("B","G"))
C<-plot_grid(MG_Volcano_FUS24,CAM_Volcano_FUS24,nrow=2,align = "v",axis = "lr",labels = c("C","H"))
D<-plot_grid(MG_Volcano_FUS72,CAM_Volcano_FUS72,nrow=2,align = "v",axis = "lr",labels = c("D","I"))

Left<-plot_grid(A,B,C,D,nrow=1)
Right<-plot_grid(Microglia_BC,Macrophage_BC,nrow=2,align = "v",axis = "tb",labels = c("E","J"))
  
Full<-plot_grid(Left,Right,rel_widths = c(5,2),align = "h",axis="tb")

setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync")
ggsave("Shams.png",width = 8.5,height = 4,units = "in",bg="white")
```



